### ISSUE TITLE
Missing documentation: How to use it

### ISSUE THREAD

**Issue by b3nn0** [annulen/webkit#112]
Hi,
I've just found this project, and since I could never switch to QtWebEngine because of all the missing features, I wanted to give this a shot.
However, I can't seem to find out how.
I cloned the repository and compiled QtWebEngine according to the respective Wiki page with Qt 5.6/Linux x86_64. Running the mini-browser worked fine. However, I can't seem to find out how to compile/link my own QtWebKit based application against this version of QtWebKit.
Back in the days when QtWebKit was a core component of Qt, I could just add QT += webkit webkitwidgets to my .pro file. Obviousely it's not that simple, so I removed those and instead tried with various combinations of different INCLUDEPATH and LIBS settings inspired by Tools/QtTestBrowser/CMakeLists.txt, but I couldn't get it to compile.

It would be nice to get a Wiki page with some information on how to actually use this QtWebKit version in practice, with a custom application.

**Comment by The-Compiler** [comment]
FWIW what I did (just trying things out for now) is to use `LD_PRELOAD`:

`$ LD_PRELOAD=~/code/qtwebkit-ng/git/build/qt/Release/lib/libQt5WebKit.so.5:~/code/qtwebkit-ng/git/build/qt/Release/lib/libQt5WebKitWidgets.so.5  my_app`

**Comment by b3nn0** [comment]
Well, right, that seems to work if you first compile your app against an old version of QtWebKit.
However, that will not work for more recent version of Qt (>= 5.6 or 5.7 or something?), that don't ship QtWebKit any more, since I can't compile my app in the first place without proper include/lib paths.

**Comment by annulen** [comment]
Thank you for report, I'm planning to fix #60 so that usage will be as simple as for original QtWebKit.
Right now you can install QtWebKit into any prefix you like and set INCLUDEPATH and LIBS manually

**Comment by annulen** [comment]
See https://github.com/annulen/webkit/wiki/Using-QtWebKit-in-your-project
