### ISSUE TITLE
Inspector UI: menu list of Styles combobox is too narrow on Windows

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#264]
![windowsstyles](https://cloud.githubusercontent.com/assets/102544/17458681/793d33a6-5c2b-11e6-91a4-01137a6999a2.png)

**Comment by Vitallium** [comment]
Sample page to reproduce the problem: https://jsbin.com/taporu/edit?html,css

**Comment by Vitallium** [comment]
And here is the problem (read the comment): https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/WebCore/rendering/RenderMenuList.cpp#L377

**Comment by Vitallium** [comment]
Fixed in master. See https://github.com/annulen/webkit/commit/42c62e2cc3243bf404c47e7796dbde3f2e112100
