### ISSUE TITLE
Some pages have italic fonts instead of normal on Windows

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#270]
https://www.google.com/fonts/specimen/Fira+Sans
https://habrahabr.ru/
![italic](https://cloud.githubusercontent.com/assets/102544/17463982/69207f26-5cdc-11e6-8234-d87068937ffc.png)

**Comment by zuojj** [comment]
me too , how to solve it ?

**Comment by annulen** [comment]
@zuojj It would help a lot if you provided minimal html page which reproduces this bug, or maybe find existing test case in `LayoutTests` directory which reproduces the problem. (this bug is windows-specific and I'm working on Linux, bug was actually reported by @Vitallium)

**Comment by bughit** [comment]
@annulen ariya/phantomjs#14471 has a test page

**Comment by annulen** [comment]
Thanks for test case, we are working on identification of bug source. Current workaround is to avoid using Windows.

**Comment by Emdek** [comment]
Note, similar behavior could be observed under Linux when using OpenGL viewports.

**Comment by lzaiko** [comment]
Hi!
I'm getting the same issue by using QT-5.8.0 with  qtwebkit-tp5 for my mini browser on Windows 10
If I upgrade to QT5.9 with qtwebkit-5.212.0-alpha2, should the issue be fixed?
If no, are you planning to make some fix in the next releases?
Thank you

**Comment by annulen** [comment]
@lzaiko By chance, can you set different font family instead of Fira Sans?

**Comment by herbmillerjr** [comment]
We're running into this now, too. Test case attached.
[fonts.zip](https://github.com/annulen/webkit/files/2832625/fonts.zip)

**Comment by herbmillerjr** [comment]
@annulen Correct.

**Comment by annulen** [comment]
To debug this issue, it's needed to put debug prints into `src/platformsupport/fontdatabases/windows/qwindowsfontengine.cpp` and `src/platformsupport/fontdatabases/windows/qwindowsfontenginedirectwrite.cpp` wherever code deals with font properties (which may be called flags or style). Also, unlocking debug messages under `#ifndef QT_NO_DEBUG_OUTPUT` in `src/platformsupport/fontdatabases/windows/qwindowsfontdatabase.cpp` may be useful

**Comment by annulen** [comment]
You may also want to check your fonts in https://github.com/RJVB/fontweightissue-qt5, but it probably won't reproduce

**Comment by herbmillerjr** [comment]
What am I looking to print? I printed the flags, and they all seem to be empty except the ShaperFlags in stringToCMap() which contains ShaperFlag::GlyphIndicesOnly.

**Comment by herbmillerjr** [comment]
It does reproduce in https://github.com/RJVB/fontweightissue-qt5! Only 12pt is correct. Any other weight goes italic.

**Comment by herbmillerjr** [comment]
Filed bug with upstream: https://bugreports.qt.io/browse/QTBUG-73660

**Comment by herbmillerjr** [comment]
Switching to freetype works around the problem: `-platform windows:fontengine=freetype`

**Comment by herbmillerjr** [comment]
Fixed upstream. Slated for Qt 5.12.3. @annulen Should this be closed?

**Comment by annulen** [comment]
Yup

**Comment by annulen** [comment]
Big thanks for investigation!
