### ISSUE TITLE
build errors with recent cmake

### ISSUE THREAD

**Issue by tjelbert** [annulen/webkit#295]
using tp3 on linux
-- Configuring done
CMake Error: install(EXPORT "WebKitTargets" ...) includes target "WebKit" which requires target "JavaScriptCore" that is not in the export set.
CMake Error: install(EXPORT "WebKitTargets" ...) includes target "WebKit" which requires target "WebCore" that is not in the export set.
-- Generating done

 cmake  3.6.1

full compile log attached
file:///var/log/sorcery/compile/webkitqt-tp3.bz2

**Comment by annulen** [comment]
You haven't attached anything so far :)

Are you trying to install SHARED_CORE build or static build? These options indeed have broken installation for now, however you may want to apply patch #277
