### ISSUE TITLE
Missing ICU library

### ISSUE THREAD

**Issue by PeterBocan** [annulen/webkit#303]
Hello guys, I wonder, how do I add ICU into the project? Any hints?

**Comment by annulen** [comment]
What platform are you using? BTW, if you follow build instructions in wiki you should not have any troubles with ICU

**Comment by PeterBocan** [comment]
I'm on Windows 10 x64, Qt 5.7 MSVC 2015.

**Comment by annulen** [comment]
build-webkit should automatically dowload archive with libraries. If you lauch cmake directly, you can alos run `Tools/Scripts/update-qtwebkit-win-libs`

**Comment by PeterBocan** [comment]
No, I don't. This is what I'm doing:

     perl.exe .\Tools\Scripts\build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\5.7\msvc2015"

**Comment by Vitallium** [comment]
@PeterBocan could you please post a build log?

**Comment by PeterBocan** [comment]
If I can find it... where it should be located?

**Comment by PeterBocan** [comment]
Okay, I was building the official repo not yours.
