### ISSUE TITLE
Help Ubuntu fatal error: private/qpdf_p.h

### ISSUE THREAD

**Issue by mlutken** [annulen/webkit#309]
I would like to contribute but I run into this error when building on Ubuntu 16.04 against Qt5.5.1.
This file is present in normal Qt source (QtGui/private/qpdf_p.h) but not in this qtwebkit.

**Comment by annulen** [comment]
Have you installed `qtbase5-private-dev` package?

**Comment by mlutken** [comment]
Thanks a lot. I was just starting (after a nights sleep :) ) that I might be missing Qt packages. It was just that since in private... but then again .. Webkit used to be included in the Qt source so private headers makes kind of sense then.

Anyway in my own project, where I use qtwebkit I have so far been building the entire Qt including Webkit... so the private headers have been there in the source :)

**Comment by annulen** [comment]
>Webkit used to be included in the Qt source so private headers makes kind of sense then.

Actually, you'll be surprised how many external Qt-based projects use private headers. Of course it creates some troubles for package maintainers so they don't like it :)

**Comment by mlutken** [comment]
But a least there is a package :-) ... a pragmatic solution

**Comment by annulen** [comment]
There will be qtwebkit packages after official release

**Comment by annulen** [comment]
Are you able to build QtWebKit now?

**Comment by mlutken** [comment]
Yes. Thanks a lot. Next step is trying to use that build in my own project. Then see if there might be something I could help with.


Sendt fra min Samsung Galaxy-smartphone.
-------- Oprindelig besked --------Fra: Konstantin Tokarev <notifications@github.com> Dato: 15/09/2016  15.42  (GMT+01:00) Til: annulen/webkit <webkit@noreply.github.com> Cc: Martin Lütken <nitram@lutken.dk>, Author <author@noreply.github.com> Emne: Re: [annulen/webkit] Help Ubuntu fatal error: private/qpdf_p.h (#309) 
Are you able to build QtWebKit now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/annulen/webkit","title":"annulen/webkit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/annulen/webkit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@annulen in #309: Are you able to build QtWebKit now?"}],"action":{"name":"View Issue","url":"https://github.com/annulen/webkit/issues/309#issuecomment-247331150"}}}
