### ISSUE TITLE
cannot open include file 'unistd.h' - Windows

### ISSUE THREAD

**Issue by jeprojects** [annulen/webkit#330]
Hi,

I am trying to compile this on windows, but am getting this error:

"cannot open include file 'unistd.h'. No such file or directory."

I understand that unistd.h is a unix based file.. 

I am guessing it has something to do with this commit: https://github.com/annulen/webkit/commit/7f6f9c87b2afb77f47fc58f52699475846c2ebc8

What should I do?

**Comment by annulen** [comment]
You are right, this is a bug on my side!

**Comment by jeprojects** [comment]
In that case I will just grabbing the source from: https://github.com/annulen/webkit/releases

Will that compile on windows ok?

Is it ok if I have MSVC 2015 64bit installed? (I want 32bit qtwebkit)

**Comment by annulen** [comment]
Yes

**Comment by annulen** [comment]
Fix is in c2f1007680903e9faa8e108306c83b86955ea5bc
