### ISSUE TITLE
GitHub: graphs don't work

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#35]
Maybe we don't enable some feature tat is required
Test page: https://github.com/annulen/webkit/graphs/traffic

**Comment by The-Compiler** [comment]
FWIW they work fine with Qt's QtWebKit here

**Comment by annulen** [comment]
They output "We tried out best, but the graph wouldn't load. Try reloading page."

No console output. Unfortunately, Inspector is not yet functional. Probably it should be highest priority task now.

**Comment by The-Compiler** [comment]
Are you trying with this repo? I'm guessing it's too big, and they give up :wink:

**Comment by annulen** [comment]
I'm testing on Traffic page, it works fine everywhere else

**Comment by annulen** [comment]
JS Debugger breaks on "Exception with thrown value: Error: SyntaxError: DOM Exception 12". Same thing occurs in Twitter when trying to open post.

**Comment by annulen** [comment]
Works in stable branch

**Comment by annulen** [comment]
This issue was one of series of JS bugs which plagued qtwebkit-1 branch. Looks like I've chosen a bad time to do rebase :)
