### ISSUE TITLE
qtwebkit-stable build failed on Ubuntu

### ISSUE THREAD

**Issue by markusschlebusch** [annulen/webkit#355]
The build of the current qtwebkit-stable failed on my Ubuntu machine as follows:

markus@ubuntu:~/webkit$ WEBKIT_OUTPUTDIR=`pwd`/build/qt Tools/Scripts/build-webkit --qt     --release     --cmakeargs="-DCMAKE_PREFIX_PATH=/opt/Qt5.4.0/5.4/gcc_64/"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BISON: /usr/bin/bison (found suitable version "3.0.4", minimum required is "2.1") 
-- Found Gperf: /usr/bin/gperf (Required is at least version "3.0.1") 
-- Found Perl: /usr/bin/perl (found suitable version "5.22.1", minimum required is "5.10.0") 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.7.0") 
-- Found Ruby: /home/markus/.rbenv/shims/ruby (found suitable version "2.3.0", minimum required is "1.9") 
-- Looking for include file features.h
-- Looking for include file features.h - found
CMake Warning at Source/cmake/ECMQueryQmake.cmake:22 (message):
  Failed call: qmake-qt5 -query "QT_INSTALL_PREFIX"
Call Stack (most recent call first):
  Source/cmake/KDEInstallDirs.cmake:431 (query_qmake)
  Source/cmake/OptionsQt.cmake:6 (include)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)

CMake Error at Source/cmake/ECMQueryQmake.cmake:23 (message):
  QMake call failed: No such file or directory
Call Stack (most recent call first):
  Source/cmake/KDEInstallDirs.cmake:431 (query_qmake)
  Source/cmake/OptionsQt.cmake:6 (include)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)

-- Configuring incomplete, errors occurred!
See also "/home/markus/webkit/build/qt/Release/CMakeFiles/CMakeOutput.log".

[CMakeOutput.txt](https://github.com/annulen/webkit/files/612793/CMakeOutput.txt)
Are there any ideas what's wrong here?

**Comment by annulen** [comment]
It cannot find your Qt.

Do you have Qt installed in `/opt/Qt5.4.0/5.4/gcc_64` like you are passing in CMAKE_PREFIX_PATH? Seems like you don't.

**Comment by markusschlebusch** [comment]
You are right. This was the wrong path. This is fixed
