### ISSUE TITLE
Use native media backends on Windows

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#36]
There is platform/graphics/win/MediaPlayerPrivateMediaFoundation.cpp, maintained as a part of WinCairo port. To use it, we need to add this code to build system and write frame drawing code similar to Cairo.

**Comment by Zero3K** [comment]
That would be great.

**Comment by annulen** [comment]
Sure, but this feature has low priority for us right now. Feel free to take it yourself or hire somebody to work on it.

**Comment by annulen** [comment]
#344 added MF player as an experimental build option.

**Comment by Zero3K** [comment]
It works well in the new beta of Otter Browser. So, I think that this issue can be closed.

**Comment by annulen** [comment]
Fixed in Alpha 2
