### ISSUE TITLE
Assembler header requires intrin.h

### ISSUE THREAD

**Issue by char101** [annulen/webkit#373]
Hi,

I'm trying to compile qtwebkit with [VisualCppTools](https://blogs.msdn.microsoft.com/vcblog/2016/02/16/try-out-the-latest-c-compiler-toolset-without-waiting-for-the-next-update-of-visual-studio/) (32 bit), which failed when compiling source\javascriptcore\assembler\MacroAssemblerX86Common.h: `'__cpuid': identifier not found`. Fixed by adding `#include <intrin.h>`.

**Comment by annulen** [comment]
Fixed in https://trac.webkit.org/changeset/210019 and c310f45a249afc03ccfdf1c821a78d652cd92ad4

**Comment by annulen** [comment]
Thanks for reporting!
