### ISSUE TITLE
MediaPlayerPrivateQt.cpp - invalid new-expression of abstract class

### ISSUE THREAD

**Issue by tjelbert** [annulen/webkit#396]
sna[shot 8ac9d5c3dc476eb7474aa7fec7b52036a6e39597
gcc-6.3.2
qt-5.7.1

In file included from /var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WTF/wtf/FastMalloc.h:26:0,
                 from /var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/config.h:75,
                 from
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.cpp:20:
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WTF/wtf/StdLibExtras.h: In instantiation of 'typename
std::_Unique_if<T>::_Single_object std::make_unique(Args&& ...) [with T = WebCore::MediaPlayerPrivateQt; Args =
{WebCore::MediaPlayer*&}; typename std::_Unique_if<T>::_Single_object = std::unique_ptr<WebCore::MediaPlayerPrivateQt,
std::default_delete<WebCore::MediaPlayerPrivateQt> >]':
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.cpp:62:57:   required from
here
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WTF/wtf/StdLibExtras.h:311:26: error: invalid new-expression of abstract
class type 'WebCore::MediaPlayerPrivateQt'
     return unique_ptr<T>(new T(std::forward<Args>(args)...));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.cpp:21:0:
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.h:40:7: note:   because
the following virtual functions are pure within 'WebCore::MediaPlayerPrivateQt':
 class MediaPlayerPrivateQt : public QAbstractVideoSurface, public MediaPlayerPrivateInterface
       ^~~~~~~~~~~~~~~~~~~~
In file included from
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.h:23:0,
                 from
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/qt/MediaPlayerPrivateQt.cpp:21:
/var/git/qt5/qt5-apps/qtwebkit-snapshots/Source/WebCore/platform/graphics/MediaPlayerPrivate.h:50:18: note:     virtual void
WebCore::MediaPlayerPrivateInterface::load(const WTF::String&, WebCore::MediaSourcePrivateClient*)
     virtual void load(const String& url, MediaSourcePrivateClient*) = 0;
                  ^~~~

Full compile log attached

[bug.zip](https://github.com/annulen/webkit/files/693199/bug.zip)

**Comment by annulen** [comment]
I guess you are buildinging with enabled MediaSource, but QtMultimedia player does not support it.

FYI, it usually does not make sense to build QtMultimedia (QtMM) player instead of GStreamer player on Unix-like systems, unless you
* have custom or 3rd-party QtMM backend (default backend uses GStreamer)
* for some reason have to use obsolete GStreamer 0.10 (we don't support it anymore directly, but QtMM still does)
* want to develop QtMM player

**Comment by annulen** [comment]
Since ce64bdf74a1f16a50033122454d967d7852d207a media source is automatically disabled if you choose QtMM
