### ISSUE TITLE
Include dir

### ISSUE THREAD

**Issue by ShalokShalom** [annulen/webkit#406]
Include dir is set to : ${KDE_INSTALL_INCLUDEDIR} - why not set to cmake vars?

When it is right in the current way, 
some doc entry is nice, to have about these 'not cmake but custom to set things'

**Comment by annulen** [comment]
KDEInstallDirs documentation says that variables of GNUInstallDirs are also supported

**Comment by abucodonosor** [comment]
The question is why ECM and kde stuff is used at all.. right now we have all header files under
$prefix/include but these should match global Qt installation I think. Maybe it has something to do with #393

**Comment by annulen** [comment]
@abucodonosor If you have something against ECM, patches are welcome

**Comment by abucodonosor** [comment]
I don't .. but it won't really work 'as is' outside kde.. see as example ecm_generate_pkgconfig_file() which 
produce , broken inclomplete files. And there are lots more..

**Comment by annulen** [comment]
This just means that ECM module for pkg-config is buggy and should be fixed. And no, ECM is not tied to KDE anyhow, and it doesn't malfunction because it's "outside of KDE"

**Comment by abucodonosor** [comment]
Well some parts really does.. ofc ECM does work are macros() after all .. all I said is won't work 'as is'..
There are things you use are not set anywhere nor does they exists.. 80% of KDEInstallDirs.cmake can
 just be deleted as example , you won't ever use or need these at all.. Also in long term $KDE_FOO 
should be $YOUR_APP_FOO and not mixed like this. Is ofc my opinion and you can do like you wish.

Here and patch to fix this one and the pkg-confi bug.. Please note I'm really tired right now and I may 
missing something.

KDE_INSTALL_INCLUDEDIR will fall back to $prefix/include that way but I guess you want Qt5_sys_header_dir so I use qmake_query() to set the install path to there.

ecm_generate_pkgconfig_file() got new DESC filed with an fall back.
the .pc file looks like this now 

`$ cat FOO/usr/lib/pkgconfig/Qt5WebKit.pc

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include/qt5/QtWebKit

Name: Qt5WebKit
Description: Qt WebKit module
Version: 5.602.2
Libs: -L/usr/lib -lQt5WebKit
Cflags: -I/usr/include/qt5/QtWebKit 
Requires: Qt5Core Qt5Gui Qt5Network
`
Patch there 
http://sigsegv.spdns.eu/~crazy/0001-fix-bug-393-and-406-v1.patch

Fell free to use this patch or parts of it.

Regards

**Comment by annulen** [comment]
@abucodonosor `KDE_INSTALL_USE_QT_SYS_PATHS` is used to switch between using Qt installation paths and normal prefixed install.

For example, Qt can be confgured (e.g. by Linux distro) to install its `include` and `lib` into different prefixes. If install prefix of QtWebkit matches Qt, `KDE_INSTALL_USE_QT_SYS_PATHS` turns on by default and paths queried from qmake are used, while if you use different prefix like /opt/qtwebkit, everything is installed into that prefix.

**Comment by abucodonosor** [comment]
Yes I know than but they use it for qml , share , plugins etc folder just not for the 'header' part.
( see qmake_query() calls )

For that CMAKE_INSTALL_INCLUDEDIR_KF5 or CMAKE_INSTALL_INCLUDEDIR/KF5 is used.

**Comment by annulen** [comment]
qml is also interesting, WK2 builds QML plugin

**Comment by abucodonosor** [comment]
This would be easy to do the macros are there already.

However please explain to me what you exactly want here.

You want to keep KDE_INSTALL_USE_QT_SYS_PATHS for install_to_auto_qt_folder like
KDE does ?

If is so we still need an qmake_query() call for the header part.
KDE_INSTALL_INCLUDEDIR is unused and will fallback to $prefix/include so maybe  this:

`if(KDE_INSTALL_USE_QT_SYS_PATHS)
    query_qmake(qt_host_header_dir QT_INSTALL_HEADERS)
    set(KDE_INSTALL_INCLUDEDIR "${qt_host_header_dir}")
else()
    set(KDE_INSTALL_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}")
endif()
`

**Comment by annulen** [comment]
What I really want to have is 

1. Installation to Qt paths, queried from qmake
2. Installation to custom prefix

KDE_INSTALL_USE_QT_SYS_PATHS as user-configurable option is not so important, and especially its name.

Also I'd like to have as little cmake code that is not 3rd party as it's possible (ECM and WebKit's cmake files without Qt suffix count as 3rd party)

**Comment by annulen** [comment]
After 3afaf9a6545141c983ea8a3f4847d9a12d930714 headers are installed to the path reported by `qmake -query QT_INSTALL_HEADERS`
