### ISSUE TITLE
Google Maps throws Font error on Windows

### ISSUE THREAD

**Issue by Vitallium** [annulen/webkit#41]
Steps to reproduce (build QtWebkit with Qt 5.6):
1) Open https://www.google.com/maps

In console you'll see this message(s):
>QWinFontEngine: unable to query transformed glyph metrics (GetGlyphOutline() failed, error 1003)... (Cannot complete this function.)

**Comment by annulen** [comment]
We need backtrace from GetGlyphOutline when error happens

**Comment by Vitallium** [comment]
Can't reproduce it anymore (tried Debug and Release versions). But keep this issue opened just in case.

**Comment by annulen** [comment]
Not reproduced
