### ISSUE TITLE
Cleanup Notifications API fallback

### ISSUE THREAD

**Issue by Emdek** [annulen/webkit#412]
Currently it uses broken `QSystemTrayIcon` (missing icon), which can lead to having two tray icons if application already has one.
If there is no reliable alternative for this approach then it at least should hide if when not needed or try to use existing one from application.
Plus set some sane icon and maybe other properties too.

**Comment by annulen** [comment]
#413 tracks hiding icon

**Comment by annulen** [comment]
#414 tracks empty icon

**Comment by annulen** [comment]
I think #413 and #414 cover this issue

**Comment by Emdek** [comment]
Uhm, sort of, still we should seek possibility to avoid it completely by default, all modern systems allow that.

**Comment by annulen** [comment]
There is a way to avoid QSystemTrayIcon - try running `notify-send`, and if it fails, fall back to tray icon. 

We need to save icon (if any) into temporary file - notifications spec requires it, that's not just a `notify-send` limitation :/

**Comment by Emdek** [comment]
@annulen, which platform? I don't have it here (Linux)...
BTW, using DBus directly is not that hard too, except requiring QtDBus.

**Comment by annulen** [comment]
It requires libnotify to be installed. And no, I don't want to link with QtDBus, and it doesn't solve anything actually, only complicates things, because notifications specification is borked.

**Comment by annulen** [comment]
Crap, I cannot get back event that it was clicked in this way

**Comment by Emdek** [comment]
We can do something similar without linking, AFAIR ``dbus-send`` is the right command but it will have the same limitation, only usable for passive notifications.
Qt really needs proper class or module to deal with that...

**Comment by annulen** [comment]
Let's rely on existing Qupzilla plugin then to do the dirty work
