### ISSUE TITLE
Memory cache hits do not appear as requests

### ISSUE THREAD

**Issue by acheleo** [annulen/webkit#416]
QWebSettings allow a user to use WebKits memory cache in a very narrow way, it is configured or cleared by the following methods:
setMaximumPagesInCache
setObjectCacheCapacities
clearMemoryCache

When there is a memory cache hit, for example, when browsing into the same website twice, it is possible that the resource itself will be fetched, without going through the regular chain of actions you do for a request.
The effect this has is that when you write code that relies on createRequest, the finished signal, etc. You cannot use the memory cache, since it doesn't necessarily generate calls to these methods.

P.S
Disk cache also causes a few problems when cache metadata does not contain an expiration date.

**Comment by annulen** [comment]
It is not possible to call createRequest for memory cache hits. You have to disable all caches to achieve that, though such configuration is not really recommended as it can expose unknown bugs or memory leaks.

Feel free to open bugs for disk cache misbehavior, though they should probably be reported against QtNetwork/QNetworkDiskCache, QtWebKit just uses it via QNAM without any special tricks
