### ISSUE TITLE
QtWebkit does not display JPEG images on Windows

### ISSUE THREAD

**Issue by tomwilliz** [annulen/webkit#417]
In short:

I have been playing with the technology preview of qtwebkit on Windows and I have a problem. I am not able to see any JPGE images on Windows with qtwebkit-tp4 or latest qtwebkit-stable. 
All is working fine if I use qtwebkit-tp3.

Any idea what might be the problem?

More details:

1. Prebuilt versions:

I have tried the official Qt 5.7.0 distribution (qt-opensource-windows-x86-msvc2015-5.7.0).

- with qtwebkit-tp3-qt57-msvc2015-x86.zip - compiled previewer.exe sample to load web pages - all looks fine (JPEG images appear in browser)
- with qtwebkit_tp4_qt57_msvc2015_x86.zip - previewer.exe sample does not show JPEG images (anything else from any web page looks fine in browser)

2. My complilation:

Also tried static builds of Qt 5.7.1 and qtwebkit-stable with the same problem (pages with JPEGs fail, anything else work fine).
Parameters I have used for compilation:

QT 5.7.1:

configure -static -release -confirm-license -opensource -platform win32-msvc2015 -nomake examples -nomake tests -openssl-linked OPENSSL_LIBS="-lssleay32 -llibeay32" -qt-zlib -qt-libpng -qt-libjpeg -icu -angle -opengl es2 -l crypt32 -l gdi32

qtwebkit-stable:

perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=D:\Qt\qt-everywhere-opensource-src-5.7.1\qtbase -DENABLE_API_TESTS=OFF -DENABLE_TEST_SUPPORT=OFF -DENABLE_INDEXED_DATABASE=OFF -DUSE_STATIC_RUNTIME=ON -DQT_BUNDLED_PNG=ON -DQT_BUNDLED_JPEG=ON"

(tried with both -DQT_BUNDLED_JPEG=ON and -DQT_BUNDLED_JPEG=OFF)

Any ideas where to look or what to try to figure out this problem?

**Comment by dmitrykx** [comment]
I can confirm this. JPEG images are not displayed.

**Comment by annulen** [comment]
Please try binaries of TP5, issue should be gone

**Comment by tomwilliz** [comment]
I confirm that the TP5 binaries (qtwebkit-tp5-qt58-msvc2015-x86.zip) work fine and jpeg images are displayed. However, I am not able to achieve that when I build qtwebkit myself. I use the following parameters: 

perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=D:\Qt\qt-everywhere-opensource-src-5.8.0\qtbase -DENABLE_API_TESTS=OFF -DENABLE_TEST_SUPPORT=OFF -DENABLE_INDEXED_DATABASE=OFF"

Also, here is the CMakeCache.txt from my build
[CMakeCache.txt](https://github.com/annulen/webkit/files/779487/CMakeCache.txt)

Can you check and see if there is anything wrong with any of the referenced libraries or settings?
What other causes could be for this problem? what should I check?

Appreciate any help. Thanks.

**Comment by annulen** [comment]
Could you run `Tools/Scripts/update-qtwebkit-win-libs` script and retry?

**Comment by tomwilliz** [comment]
I just get this message:

Checking Last-Modified date of qtwebkit-libs-win.zip...
Current qtwebkit-libs-win is up to date

**Comment by Vitallium** [comment]
@tomwilliz @annulen I'll update libs ASAP.

**Comment by Vitallium** [comment]
I've updated dependencies. Please run `Tools/Scripts/update-qtwebkit-win-libs` and try to build again.

**Comment by tomwilliz** [comment]
I have just tried and the problem persists. The new qtwebkit-libs-win.zip is downloaded, but by looking to its content, it seems that only some ICU debug libraries were added. No changes related to jpeg library or any other libraries.

**Comment by tomwilliz** [comment]
@Vitallium can you please re-check the libraries from qtwebkit-libs-win.zip?

**Comment by NiHoT** [comment]
Same issue for me. Redundant posts here : https://github.com/annulen/webkit/issues/499 and here : https://github.com/Vitallium/qtwebkit-libs-win/issues/1

Sorry I just saw this thread today

**Comment by annulen** [comment]
We can get rid of this issue in a sense that local builds will never be broken when official binaries work.

Inside Qt CI system we cannot use qtwebkit-libs-win.zip, and we opted for Conan package manager (http://conan.io). It would be logical to use Conan in update-qtwebkit-win-libs as well. It's not hard at all, I think anyone here can make a patch.

Bonus points if
* Compiler can be chosen via command line option (msvc2015, msvc2017, mingw x.y)
* Conan is installed via autoinstaller module, that would require running it as a python module, not as a command line appplication

**Comment by annulen** [comment]
Our current conanfiles are in qt5 repo, separate file for each compiler:
* http://code.qt.io/cgit/qt/qt5.git/tree/coin/provisioning/qtci-windows-10-x86_64/conanfiles/qtwebkit.txt
* http://code.qt.io/cgit/qt/qt5.git/tree/coin/provisioning/qtci-windows-10-x86/conanfiles/qtwebkit.txt
* http://code.qt.io/cgit/qt/qt5.git/tree/coin/provisioning/qtci-windows-7-x86/conanfiles/qtwebkit.txt

**Comment by annulen** [comment]
Should be fined now, please run update-qtwebkit-win-libs again, remove Qt5WebKit.dll and relink it. Please reopen if it doesn't work
