### ISSUE TITLE
OS X version uses -l compiler flags instead of -framework

### ISSUE THREAD

**Issue by dmitrykx** [annulen/webkit#422]
First of all I'd like to say thank you for porting QtWebKit for OS X.

Using TP4 and official Qt 5.7.1 on OS X 10.10. Compilation of my webkit-based project has succeeded, but the linking stage has failed. This is because of the wrong linker options:

    ld: library not found for -lQt5WebKitWidgets

If I go to the current project's Makefile and replace -l options with -framework options, linking succeeds. -l options are solely used by QtWebKit. Other Qt libraries use the -framework option.

**Comment by annulen** [comment]
Please try patch #388

**Comment by annulen** [comment]
This should be fixed in qtwebkit-stable since 1686903
