### ISSUE TITLE
cmake files not exporting the necessary include directories

### ISSUE THREAD

**Issue by dougmassay** [annulen/webkit#427]
Existing Qt5 cmake projects that use QtWebKitWidgets are failing to build with this version of WebKit because the cmake files are not exporting the necessary include directories to be searched. This will break a lot of existing code out there. Including [Sigil](https://github.com/Sigil-Ebook/Sigil/issues/277).

**Comment by annulen** [comment]
Include directories are exported. Search for INTERFACE_INCLUDE_DIRECTORIES in installed cmake files

**Comment by dougmassay** [comment]
All I know is that this project builds fine with the community version of QtWebKit, but fails to find the includes when using this fork. The downstream Arch maintainer pointed me this way when I registered the same complaint there.

**Comment by antonio-rojas** [comment]
Minimal test case:
`project( qtwebkit-test )
cmake_minimum_required(VERSION 3.0)

find_package(Qt5 COMPONENTS Core WebKit)
message("Include dirs: ${Qt5Core_INCLUDE_DIRS} ${Qt5WebKit_INCLUDE_DIRS}")
`

With upstream qtwebkit:
`-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Include dirs: /usr/include/qt/;/usr/include/qt/QtCore;/usr/lib/qt//mkspecs/linux-g++ /usr/include/qt/;/usr/include/qt/QtWebKit;/usr/include/qt/QtGui;/usr/include/qt/QtCore;/usr/lib/qt//mkspecs/linux-g++;/usr/include;/usr/include/qt/QtNetwork
-- Configuring done
-- Generating done
-- Build files have been written to: /home/antonio/Software/test/testcmake
`

With this version:
`-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Include dirs: /usr/include/qt/;/usr/include/qt/QtCore;/usr/lib/qt//mkspecs/linux-g++ 
-- Configuring done
-- Generating done`

**Comment by dougmassay** [comment]
In addition to the Qt5WebKit_INCLUDE_DIRS (and Qt5WebKitWidget_INCLUDE_DIRS) variable not being generated, the `<module>_LIBRARIES` variables for QtWebKit(Widgets) aren't being exported either.

Adding:

`message("Libraries: ${Qt5Core_LIBRARIES} ${Qt5WebKit_LIBRARIES}")`

to the above qtwebkit-test cmake project produces the following output with upstream QtWebkit:

`Libraries: Qt5::Core Qt5::WebKit`

With this version it produces:

`Libraries: Qt5::Core`

**Comment by annulen** [comment]
Ah, you mean legacy variables. You should really use `target_link_libraries(Qt5::WebKitWidgets)` instead, but I can add those too

**Comment by annulen** [comment]
https://github.com/annulen/webkit/wiki/Using-QtWebKit-in-your-project#cmake

**Comment by dougmassay** [comment]
I appreciate the directions for how to use your QtWebKit implementation, but I have src that needs to build against more than just your implementation of QtWebKit. It has to build with Qt5.4+, CMAKE 2.8+, community QtWebKit (and any other QtWebKit a distro might decide to implement) on three platforms.

I (and probably a ton of other maintainers of cmake projects that utilize QtWebKit) would certainly appreciate it if those "legacy" variables were added. They're not obsolete after all. They're still mentioned in the official cmake documentation.

Thanks in advance.

**Comment by annulen** [comment]
I'm not closing this bug, fix is coming soon. Nobody reported it yet so I thought everyone was happy :)

**Comment by dougmassay** [comment]
Glad to hear it. It will be much appreciated! :)

**Comment by annulen** [comment]
Please try patch #436

**Comment by annulen** [comment]
You can get raw diff from https://patch-diff.githubusercontent.com/raw/annulen/webkit/pull/436.diff

**Comment by demmm** [comment]
Using these 2 commits:
https://github.com/annulen/webkit/commit/afe18f7d13f5c825ce323bfb756b249c0e163554
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qtwebkit/0012-install-additional-pri-files.patch
added to a a build of https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5
Results in a successful build of two previous failing, Sigil 0.9.7 & Quassel 0.12.4.

**Comment by annulen** [comment]
FWIW, 0012-install-additional-pri-files.patch cannot affect external project that do not use qmake
Do you have any other projects to test?

**Comment by annulen** [comment]
Fixed in 1467a94564bb2f9631c93af5850b25ccdd4a0cf1
