### ISSUE TITLE
Can't download pdfjs PDFs

### ISSUE THREAD

**Issue by The-Compiler** [annulen/webkit#428]
Clicking the download icon on https://mozilla.github.io/pdf.js/web/viewer.html works fine with the old QtWebKit or QtWebEngine, but fails with -NG with 'Protocol "blob" is unknown'.

**Comment by annulen** [comment]
It works fine here

**Comment by annulen** [comment]
Confirmed

**Comment by annulen** [comment]
`ENABLE(BLOB)` guards were removed from WebKit, but Qt-specific code still has them, preventing compilation of blob support code

**Comment by annulen** [comment]
Fixed  in 6d52d62517deea59325ac9cc82ce1b2d8edcafbc
