### ISSUE TITLE
Inspector disappears when inspected tab is hidden

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#446]
It happens when switching from inspected tab to other and then back in Otter, or when minimizing MDI window

**Comment by Emdek** [comment]
Here is minimal test case:
https://otter-browser.org/tmp/test-qtwebkit-tabs.tar.bz2

**Comment by Emdek** [comment]
Fixed in 6527e4f419e108dad9b698f1a798d8c5369754e0.

**Comment by annulen** [comment]
Similar issue was fixed in 2009 in the same way: https://bugs.webkit.org/show_bug.cgi?id=31851
