### ISSUE TITLE
@font-face fails over 47pt

### ISSUE THREAD

**Issue by herbmillerjr** [annulen/webkit#452]
[https://drive.google.com/file/d/0B7YOzO1qO6-KelYtVE9zRlNYSEE/view?usp=sharing](url)

Tried to slim down the example as best I could. When setting a font family via the @font-face css directive, using that font family only displays under 48pt. Higher and it disappears. The example bumps the pt size up 10 every seconds to demonstrate.

Installing the font into a system path where fontconfig can see it, removing the @font-face directive and using the font family that way does not reproduce the bug.

I'm seeing this across multiple hardware configurations, using the QtTestBrowser built against Qt5.8. Tested with ProximaNova, Ubuntu, Noto Sans, and Avenir fonts.

**Comment by annulen** [comment]
Please attach test case (maybe compressed if it is large) to the issue directly

**Comment by annulen** [comment]
Also, is it reproducible with legacy QtWebKit? If yes, it's a better idea to open issue in bugreports.qt.io, also JIRA does not forbid .html attachments

**Comment by herbmillerjr** [comment]
[font-bug.zip](https://github.com/annulen/webkit/files/800251/font-bug.zip)

Done.

Tried against Qt/QtWebkit from Debian Jessie (version 5.3.2) with no issues.

Subjectively: I didn't notice this until around November/December last year. Tried backtracking through the commits and rebuilding, but couldn't seem to find which one introduced it (if indeed there was a commit that introduced it). This was also around the time I starting looking into Qt5.8, but when I went back and checked Qt5.7, I saw the same thing.

**Comment by annulen** [comment]
It may be bug in Qt

**Comment by herbmillerjr** [comment]
If I open a ticket with them, how can I demonstrate that? If it's a bug in Qt, would the same thing happen with QtWebEngine?

**Comment by annulen** [comment]
No, QtWebEngine does not use Qt to handle fonts. If this is Qt bug it should reproduce in test case with QLabel and large font

**Comment by herbmillerjr** [comment]
I'm not sure how to set that up. I don't know how to a webfont type of declaration with @font-face with a Qt widget stylesheet.

**Comment by annulen** [comment]
No, it shouldn't have anything to do with Qt style sheets and web fonts.

Web font in QtWebKit is implemented as QRawFont initialized with QByteArray with font file contents, which is painted with QPainter::drawGlyphRun. I think it should not be important here, you can just set your font family in QFont and set it to QLabel (e.g. in Qt Designer)

**Comment by herbmillerjr** [comment]
Not replicating when setting font on QLabel in QtDesigner and executing application.

**Comment by herbmillerjr** [comment]
Scratch the inconsistent comment. That was a problem with my Javascript.

**Comment by aleray** [comment]
Hi, any update on this issue? I have the same problem. Thanks

**Comment by annulen** [comment]
Not yet. I planned to create test case with QRawFont but it slipped away

**Comment by annulen** [comment]
Ok, found my old https://github.com/annulen/test_qrawfont. With Qt 5.8.0 QRawFont paints Ubuntu-R.ttf up to size 63px, starting from 64px there is no output. With previous versions, tested up to 5.7.0, larger fonts is painted correctly. So this is a regression in QRawFont, introduced in 5.8.0 or 5.7.1

**Comment by aleray** [comment]
Thanks for this test annulen! What is the next step? Should we raise the issue upstream? Thanks

**Comment by annulen** [comment]
Yes, I'll make bug report

**Comment by herbmillerjr** [comment]
Confirmed issue is not present in 5.7.1.

**Comment by annulen** [comment]
https://bugreports.qt.io/browse/QTBUG-59799

**Comment by aleray** [comment]
Thanks a lot!

**Comment by annulen** [comment]
Fix: https://codereview.qt-project.org/#/c/190673/1

**Comment by annulen** [comment]
Fix coming in Qt 5.9
