### ISSUE TITLE
Failure - Building on Win10/MSVC2015/Qt5.8.0

### ISSUE THREAD

**Issue by NiHoT** [annulen/webkit#469]
All is in the subject, I'am trying to build QtWebKit Reloaded on Win10/MSVC2015/Qt5.8.0 (32bits)

Here is the command line I used : 
`perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.8.0\5.8\msvc2015" --prefix=C:\Qt\Qt5.8.0\5.8\msvc2015`

After a while, I end up with this error :

> "C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\ALL_BUILD.vcxproj" (cible par défaut) (1) ->
> "C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Tools\DumpRenderTree\DumpRenderTree.vcxproj" (cible par défaut) (4) ->
> "C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj" (cible par défaut) (13) ->
> (Link cible) ->
>   WebCore.lib(IDBRequest.obj) : error LNK2001: unresolved external symbol "public: static class JSC::Structure * __cdecl JSC::Structure::create(class JSC::VM &,class JSC::JSGlobalObject *,class JSC::JSValue,class JSC::TypeInfo const &,struct JSC::ClassInfo const *,unsigned char,unsigned int)" (?create@Structure@JSC
> @@SAPAV12@AAVVM@2@PAVJSGlobalObject@2@VJSValue@2@ABVTypeInfo@2@PBUClassInfo@2@EI@Z) [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
>   WebCore.lib(IDBFactory.obj) : error LNK2001: unresolved external symbol "public: static class JSC::Structure * __cdecl JSC::Structure::create(class JSC::VM &,class JSC::JSGlobalObject *,class JSC::JSValue,class JSC::TypeInfo const &,struct JSC::ClassInfo const *,unsigned char,unsigned int)" (?create@Structure@JSC
> @@SAPAV12@AAVVM@2@PAVJSGlobalObject@2@VJSValue@2@ABVTypeInfo@2@PBUClassInfo@2@EI@Z) [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
>   WebCore.lib(IDBCursor.obj) : error LNK2001: unresolved external symbol "public: static class JSC::Structure * __cdecl JSC::Structure::create(class JSC::VM &,class JSC::JSGlobalObject *,class JSC::JSValue,class JSC::TypeInfo const &,struct JSC::ClassInfo const *,unsigned char,unsigned int)" (?create@Structure@JSC@
> @SAPAV12@AAVVM@2@PAVJSGlobalObject@2@VJSValue@2@ABVTypeInfo@2@PBUClassInfo@2@EI@Z) [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
>   WebCore.lib(IDBOpenDBRequest.obj) : error LNK2001: unresolved external symbol "public: static class JSC::Structure * __cdecl JSC::Structure::create(class JSC::VM &,class JSC::JSGlobalObject *,class JSC::JSValue,class JSC::TypeInfo const &,struct JSC::ClassInfo const *,unsigned char,unsigned int)" (?create@Structu
> re@JSC@@SAPAV12@AAVVM@2@PAVJSGlobalObject@2@VJSValue@2@ABVTypeInfo@2@PBUClassInfo@2@EI@Z) [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
>   WebCore.lib(IDBCursorWithValue.obj) : error LNK2001: unresolved external symbol "public: static class JSC::Structure * __cdecl JSC::Structure::create(class JSC::VM &,class JSC::JSGlobalObject *,class JSC::JSValue,class JSC::TypeInfo const &,struct JSC::ClassInfo const *,unsigned char,unsigned int)" (?create@Struc
> ture@JSC@@SAPAV12@AAVVM@2@PAVJSGlobalObject@2@VJSValue@2@ABVTypeInfo@2@PBUClassInfo@2@EI@Z) [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
>   C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\bin32\Qt5WebKit.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\Toni\Desktop\webkit-qtwebkit-tp5\WebKitBuild\Release\Source\WebKit\WebKit.vcxproj]
> 

I don't understand, I carefully followed these instructions : https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows
Can anyone help me?

Thanks in advance,
Regards

**Comment by annulen** [comment]
Are you aware that there are prebuilt binaries for your configuration?

**Comment by NiHoT** [comment]
No! Where can I find it?

**Comment by annulen** [comment]
https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5

**Comment by NiHoT** [comment]
Nice! I am going to try this right now. 
Thanks!
Any idea for my building isssue?

**Comment by annulen** [comment]
Production binaries use ENABLE_TEST_SUPPORT=OFF cmake option. Testing code may indeed fail to build on Windows

**Comment by NiHoT** [comment]
Sorry but I am not familiar with cmake. Is adding -DENABLE_TEST_SUPPORT=OFF to cmakeargs ok?
Is this command correct to you : `perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.8.0\5.8\msvc2015 -DENABLE_TEST_SUPPORT=OFF" --prefix=C:\Qt\Qt5.8.0\5.8\msvc2015`

**Comment by annulen** [comment]
Looks good to me

**Comment by NiHoT** [comment]
Sorry but, still not working. Full log attached in case you have time for a quick look..
[log.txt](https://github.com/annulen/webkit/files/831403/log.txt)

**Comment by annulen** [comment]
AFAIU, actual error in you last log is 
```
  Generating ../../DerivedSources/WebCore/HTMLEntityTable.cpp
  Generating ../../DerivedSources/WebCore/HTTPHeaderNames.cpp, ../../DerivedSources/WebCore/HTTPHeaderNames.gperf, ../../DerivedSources/WebCore/HTTPHeaderNames.h
  'C:/Program' is not recognized as an internal or external command,
  operable program or batch file.
  Failed to run gperf.
```
Looks like you are using gperf in path that contains space symbol, this may not work properly

**Comment by NiHoT** [comment]
Yes, good guess. I was on a VM for this build, gperf was installed in "Program File"... 
I ensure none of the programs called has spaces in his path. 
I restart building, and it finally ends with the error I had in the first post. 
Again Full log attached in case.
[log.txt](https://github.com/annulen/webkit/files/837764/log.txt)

**Comment by NiHoT** [comment]
Any idea?

**Comment by annulen** [comment]
Please try following patch:
```diff
diff --git a/Source/WebCore/Modules/indexeddb/IDBRequest.cpp b/Source/WebCore/Modules/indexeddb/IDBRequest.cpp
index c6a8b1e105f..321fca176ad 100644
--- a/Source/WebCore/Modules/indexeddb/IDBRequest.cpp
+++ b/Source/WebCore/Modules/indexeddb/IDBRequest.cpp
@@ -28,6 +28,8 @@

 #if ENABLE(INDEXED_DATABASE)

+#include "StructureInlines.h"
+
 namespace WebCore {

 IDBRequest::IDBRequest(ScriptExecutionContext* context)
```

**Comment by NiHoT** [comment]
Thanks, I am going to try this ASAP. For now I can't because of the dropbox broken link in the script: https://dl.dropboxusercontent.com/u/30021413/qtwebkit-libs-win.zip
Problem with your Dropbox account?
I am going to try again tomorrow.

**Comment by annulen** [comment]
You can download same file from https://github.com/Vitallium/qtwebkit-libs-win/releases/download/2015/qtwebkit-libs-win.zip

**Comment by NiHoT** [comment]
Ok, so I tried your patch, I had to apply it in other files where the same error occurs :

	* Source/WebCore/Modules/indexeddb/IDBRequest.cpp
	* Source/WebCore/Modules/indexeddb/IDBFactory.cpp
	* Source/WebCore/Modules/indexeddb/IDBCursor.cpp
	* Source/WebCore/Modules/indexeddb/IDBOpenDBRequest.cpp
	* Source/WebCore/Modules/indexeddb/IDBCursorWithValue.cpp


Others errors occur. See below.
(The DLLs seem built anyway, weird)



[Log.txt](https://github.com/annulen/webkit/files/862250/Log.txt)



```
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_hybridPixmap.vcxproj" (default target) (19) ->
(Link target) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_hybridPixmap.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_hybridPixmap.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_hyb
ridPixmap.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qgraphicswebview.vcxproj" (default target) (20) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qgraphicswebview.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qgraphicswebview.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst
_qgraphicswebview.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qobjectbridge.vcxproj" (default target) (21) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qobjectbridge.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qobjectbridge.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qo
bjectbridge.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebelement.vcxproj" (default target) (22) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebelement.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebelement.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qweb
element.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebframe.vcxproj" (default target) (23) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebframe.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebframe.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebfr
ame.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebhistory.vcxproj" (default target) (24) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebhistory.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebhistory.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qweb
history.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebhistoryinterface.vcxproj" (default target) (25) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebhistoryinterface.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebhistoryinterface.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests
\tst_qwebhistoryinterface.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebinspector.vcxproj" (default target) (26) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebinspector.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebinspector.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qw
ebinspector.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebpage.vcxproj" (default target) (27) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebpage.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebpage.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebpag
e.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebsecurityorigin.vcxproj" (default target) (28) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebsecurityorigin.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebsecurityorigin.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\t
st_qwebsecurityorigin.vcxproj]


"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebview.vcxproj" (default target) (29) ->
  MSVCRT.lib(exe_winmain.obj) : error LNK2019: symbole externe non rÚsolu _WinMain@16 rÚfÚrencÚ dans la fonction "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [C:\Users\test\Desktop\webkit-qtwebkit-stable\W
ebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebview.vcxproj]
  C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\bin32\tst_qwebview.exe : fatal error LNK1120: 1 externes non rÚsolus [C:\Users\test\Desktop\webkit-qtwebkit-stable\WebKitBuild\Release\Source\WebKit\qt\tests\tst_qwebvie
w.vcxproj]

    118 Warning(s)
    22 Error(s)

Time Elapsed 01:04:36.72
```

**Comment by annulen** [comment]
Nothing weird in that DLLs are built, all errors are from building executables of tests

**Comment by NiHoT** [comment]
Ok thanks, that is what I thought. But I built with this command line : 

` perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.8.0\5.8\msvc2015 -DENABLE_TEST_SUPPORT=OFF" --prefix=C:\Qt\Qt5.8.0\5.8\msvc2015`

 Executables of tests shouldn't be built, no? Do I have to add another parameter to skip building executables of tests?

**Comment by annulen** [comment]
You can pass ENABLE_API_TESTS=OFF. However, it would be better to find a fix instead.

Could you test this patch:
```diff
diff --git a/Source/WebKit/PlatformQt.cmake b/Source/WebKit/PlatformQt.cmake
index 0612f4c97d5..c554628d5b9 100644
--- a/Source/WebKit/PlatformQt.cmake
+++ b/Source/WebKit/PlatformQt.cmake
@@ -661,9 +661,6 @@ if (MSVC)
     string(REPLACE "INCREMENTAL:YES" "INCREMENTAL:NO" replace_CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO})
     set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${replace_CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} /INCREMENTAL:NO")

-    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")
-    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")
-
     list(APPEND WebKit_INCLUDE_DIRECTORIES
         ${DERIVED_SOURCES_WEBKIT_DIR}
     )
diff --git a/Tools/QtTestBrowser/CMakeLists.txt b/Tools/QtTestBrowser/CMakeLists.txt
index 485cd0ca15b..ab625f6e51e 100644
--- a/Tools/QtTestBrowser/CMakeLists.txt
+++ b/Tools/QtTestBrowser/CMakeLists.txt
@@ -67,3 +67,7 @@ include_directories(SYSTEM ${QtTestBrowser_SYSTEM_INCLUDE_DIRECTORIES})
 add_executable(QtTestBrowser ${QtTestBrowser_SOURCES})
 target_link_libraries(QtTestBrowser ${QtTestBrowser_LIBRARIES})
 set_target_properties(QtTestBrowser PROPERTIES FOLDER "Tools")
+
+if (${CMAKE_BUILD_TYPE} MATCHES "Release")
+    set_target_properties(QtTestBrowser PROPERTIES WIN32_EXECUTABLE ON)
+endif ()
```

**Comment by NiHoT** [comment]
Yeah! It works. Thanks for your help!

```
    119 Warning(s)
    0 Error(s)

Time Elapsed 00:59:53.23

====================================================================
 WebKit is now built (1h:05m:26s).
 To run MiniBrowser with this newly-built code, use the
 "Tools\Scripts/run-minibrowser" script.
====================================================================
```
The command I used : 
> perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.8.0\5.8\msvc2015" --prefix=C:\Qt\Qt5.8.0\5.8\msvc2015


Are you going to commit those modification in stable branch?

**Comment by NiHoT** [comment]
Maybe I can do a pull request with all those modifications?
