### ISSUE TITLE
Crashes on Twitch chat, etc.

### ISSUE THREAD

**Issue by Zero3K** [annulen/webkit#47]
When viewing the chatroom of a Twitch stream (such as http://www.twitch.tv/twitchplayspokemon) or a VOD of a Twitch stream (such as https://www.twitch.tv/sethbling/v/57007807) for a while, it crashes. I have attached a crash log generated by WinCrashReport.
[webkit-crashlog.zip](https://github.com/annulen/webkit/files/201021/webkit-crashlog.zip)

**Comment by annulen** [comment]
This tracker is not intended for bugs which affect QtWebKit versions corresponding to official Qt releases. See https://github.com/annulen/webkit/wiki/Reporting-Bugs
