### ISSUE TITLE
tp5:Building QtWebKit on Windows (MSYS)  debug failed:too many sections

### ISSUE THREAD

**Issue by xichuangtech** [annulen/webkit#475]
D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\rendering\RenderingAllInOne.cpp.obj: too many sections (43214)
C:\Users\ADMINI~1\AppData\Local\Temp\ccCHvfM9.s: Assembler messages:
C:\Users\ADMINI~1\AppData\Local\Temp\ccCHvfM9.s: Fatal error: can't write CMakeFiles\WebCore.dir\rendering\RenderingAllInOne.cpp.obj: File too big
D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\rendering\RenderingAllInOne.cpp.obj: too many sections (43214)
C:\Users\ADMINI~1\AppData\Local\Temp\ccCHvfM9.s: Fatal error: can't close CMakeFiles\WebCore.dir\rendering\RenderingAllInOne.cpp.obj: File too big
Source\WebCore\CMakeFiles\WebCore.dir\build.make:12216: recipe for target 'Source/WebCore/CMakeFiles/WebCore.dir/rendering/RenderingAllInOne.cpp.obj' failed
mingw32-make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/rendering/RenderingAllInOne.cpp.obj] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\css\CSSAllInOne.cpp.obj: too many sections (32890)
C:\Users\ADMINI~1\AppData\Local\Temp\ccXoJW4f.s: Assembler messages:
C:\Users\ADMINI~1\AppData\Local\Temp\ccXoJW4f.s: Fatal error: can't write CMakeFiles\WebCore.dir\css\CSSAllInOne.cpp.obj: File too big
D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\css\CSSAllInOne.cpp.obj: too many sections (32890)
C:\Users\ADMINI~1\AppData\Local\Temp\ccXoJW4f.s: Fatal error: can't close CMakeFiles\WebCore.dir\css\CSSAllInOne.cpp.obj: File too big
Source\WebCore\CMakeFiles\WebCore.dir\build.make:12417: recipe for target 'Source/WebCore/CMakeFiles/WebCore.dir/css/CSSAllInOne.cpp.obj' failed
mingw32-make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/css/CSSAllInOne.cpp.obj] Error 1
                            D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\dom\DOMAllInOne.cpp.obj: too many sections (36708)
C:\Users\ADMINI~1\AppData\Local\Temp\ccSsyHgL.s: Assembler messages:
C:\Users\ADMINI~1\AppData\Local\Temp\ccSsyHgL.s: Fatal error: can't write CMakeFiles\WebCore.dir\dom\DOMAllInOne.cpp.obj: File too big
D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\WebCore.dir\dom\DOMAllInOne.cpp.obj: too many sections (36708)
C:\Users\ADMINI~1\AppData\Local\Temp\ccSsyHgL.s: Fatal error: can't close CMakeFiles\WebCore.dir\dom\DOMAllInOne.cpp.obj: File too big
Source\WebCore\CMakeFiles\WebCore.dir\build.make:12392: recipe for target 'Source/WebCore/CMakeFiles/WebCore.dir/dom/DOMAllInOne.cpp.obj' failed
mingw32-make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/dom/DOMAllInOne.cpp.obj] Error 1
CMakeFiles\Makefile2:760: recipe for target 'Source/WebCore/CMakeFiles/WebCore.dir/all' failed
mingw32-make[1]: *** [Source/WebCore/CMakeFiles/WebCore.dir/all] Error 2
Makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by annulen** [comment]
It is not possible to build debug configuration with 32-bit compiler. Try 64-bit version of MinGW (this doesn't mean you have to build 64-bit binaries, you can use -m32 flag)

**Comment by annulen** [comment]
You can get latest snapshot from http://code.qt.io/cgit/qt/qtwebkit.git/log/?h=wip/next (wip/next branch), it has a workaround that makes QtWebKit building with debug info only for API classes. This allows to make debug build with 32-bit compiler, though debug info is not as thorough as it could be

**Comment by BlockMechanic** [comment]
I used this :- -DCMAKE_CXX_FLAGS=-Wa,-mbig-obj -DCMAKE_CXX_FLAGS:STRING="-O3"

**Comment by annulen** [comment]
@BlockMechanic Did you use 64-bit version of mingw?

**Comment by BlockMechanic** [comment]
i am building in x86 to ensure it works across all versions
