### ISSUE TITLE
Debug binaries for Windows

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#479]
Problem: 32-bit toolchains hit memory limit when compiling or linking debug QtWebKit on Windows.

MinGW - should be solved by f2b3798825093b5baa78bb642ba97ef276d337de that adds USE_MINIMAL_DEBUG_INFO option. However it cannot be straightforwardly applied to MSVC, because it does not have negative counterpart for /Zi

We should also make sure that debug DLLs and PDBs find their way to artifacts (`jom install` results)

**Comment by pmh4514** [comment]
Agreed (by the way very thankful for this project, I just found it, and it's keeping me from going down the rabbet hole of porting my QWebKit app to QWebEngine just so I can upgrade to 5.8
These precompiled binaries for MSVC2015 were very helpful, having the debug set would be great as well.

**Comment by annulen** [comment]
Coin produces proper debug+release binary archives now for MSVC x64 and MinGW. MSVC x86 got .pdb files for release, debug is not yet building. macOS has troubles with debug version of framework

**Comment by annulen** [comment]
Fixed in 631aee7e680a33c2426ad6f9aee015b016ad30bb for MSVC/x86
