### ISSUE TITLE
WebKit installation after building on OSX

### ISSUE THREAD

**Issue by NiHoT** [annulen/webkit#481]
Hello, its me again! I experience a little problem for installing WebKit module in the Qt repertory. This time  on OSX. 

After building WebKit on OSX with this command : 
`perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=C:\Qt\Qt5.6.2\5.6\msvc2015" --prefix=C:\Qt\Qt5.6.2\5.6\msvc2015`

 I go to `./WebKitBuild/Realease`  and execute the command : 
`make install`

The command successfully install the module in Qt directory. But there is a problem if I tried to use the module, an error occurs : 
`ld: library not found for -lQt5WebKitWidgets`

In order to solve this problem, I had to add: 
`QT.[module].module_config = lib_bundle`
In the qt_lib_webkit.pri & qt_lib_webkitwidgets.pri

Is this normal? Does the 'make install' should be modified?

Thanks in advance

**Comment by annulen** [comment]
#388 will fix this

**Comment by annulen** [comment]
This should be fixed since 1686903
