### ISSUE TITLE
Crash on OSX 10.7

### ISSUE THREAD

**Issue by NiHoT** [annulen/webkit#485]
Hi,
I just built Wekbit on OSX 10.12 with xCode 7.3/Qt5.6.2. I also built a test app that I deployed. 
When I execute this app on OSX 10.8.5, it crashes. I think this comes from default building options...

> Dyld Error Message:
>   Symbol not found: ___exp10
>   Referenced from: /Users/USER/Desktop/TestApp.app/Contents/MacOS/../Frameworks/QtWebKit.framework/Versions/5.602.3/QtWebKit
>   Expected in: /usr/lib/libSystem.B.dylib

[log.txt](https://github.com/annulen/webkit/files/882331/log.txt)

Any idea?

**Comment by annulen** [comment]
If you are building macOS binaries for redistribution you have to specify minimum deployment version and SDK. When building QtWebKit, pass CMAKE_OSX_SYSROOT and CMAKE_OSX_DEPLOYMENT_TARGET variables to CMake

**Comment by annulen** [comment]
Also note that we don't support targeting OS X < 10.10 for now, because upstream dropped 10.9 support before our branch point. It may be easy to get back 10.9 support if you want it (revert a few bits from patches found by `git log --grep=Mountain Lion`), but I have no idea how hard will be to get as low as 10.7

**Comment by annulen** [comment]
Is it your product: https://www.webacappella.com/? From quick glance it looks like falling back to QtWebKit 5.6.x (maintained legacy branch) is not an option, so you might need to raise system requirements

**Comment by NiHoT** [comment]
Yes this is my product! So I built Webkit (stable), this time with xCode8.3/SDK10.12/Qt5.6.2. I added 

> -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
(Doesn't work with 10.7&10.8 like you said but 10.9 is ok)

And it runs well on OSX 10.7!

Thanks again
