### ISSUE TITLE
Building with xCode8.3 & SDK10.12

### ISSUE THREAD

**Issue by NiHoT** [annulen/webkit#497]
I just tried to built Webkit TP5 with xCode8.3 / SDK10.12 / Qt5.6.2. I had an error :

> 'libxml/parser.h' file not found

I had to create a symlink `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml`
 to
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2/libxml`

Is this normal? Bad cmake configuration? 
(I had not this issue with Webkit stable)

> [ 49%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/html/HTMLElementsAllInOne.cpp.o
>  In file included from /Users/Macdev/Desktop/webkit-qtwebkit-tp5/Source/WebCore/inspector/InspectorAllInOne.cpp:31:
>  In file included from /Users/Macdev/Desktop/webkit-qtwebkit-tp5/Source/WebCore/inspector/DOMPatchSupport.cpp:46:
>  In file included from /Users/Macdev/Desktop/webkit-qtwebkit-tp5/Source/WebCore/xml/parser/XMLDocumentParser.h:33:
>  /Users/Macdev/Desktop/webkit-qtwebkit-tp5/Source/WebCore/xml/XMLErrors.h:35:10: fatal error: 'libxml/parser.h' file not found
>  #include <libxml/parser.h>
>           ^
>  1 error generated.
>  make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/inspector/InspectorAllInOne.cpp.o] Error 1
>  make[2]: *** Waiting for unfinished jobs....
>  1 warning generated.
>  make[1]: *** [Source/WebCore/CMakeFiles/WebCore.dir/all] Error 2
>  make: *** [all] Error 2

**Comment by annulen** [comment]
You are getting there because of https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/cmake/OptionsQt.cmake#L342

This code is needed because otherwise cmake prefers MacPorts version of libxml2 to the system one. And it could be what one wants, if it wasn't happening in Qt CI system that produces official binaries :)

It's also impossible to restrict search to system or SDK paths only without rewiriting FindLibXml2 module, so I had to hardcode include path to `${CMAKE_OSX_SYSROOT}/usr/include/libxml2`. Could you check what path is in different SDK versions?

**Comment by annulen** [comment]
Could you check if this patch helps?
```diff
diff --git a/Source/cmake/OptionsQt.cmake b/Source/cmake/OptionsQt.cmake
index a4b4fa4fe60..84931e48644 100644
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -340,10 +340,17 @@ else ()
 endif ()
 
 if (MACOS_FORCE_SYSTEM_XML_LIBRARIES)
-    set(LIBXML2_INCLUDE_DIR "${CMAKE_OSX_SYSROOT}/usr/include/libxml2")
+    find_path(LIBXML2_INCLUDE_DIR NAMES libxml/xpath.h
+        PATHS "${CMAKE_OSX_SYSROOT}/usr/include"
+        PATH_SUFFIXES libxml2
+    )
     set(LIBXML2_LIBRARIES xml2)
+
     if (ENABLE_XSLT)
-        set(LIBXSLT_INCLUDE_DIR "${CMAKE_OSX_SYSROOT}/usr/include/libxslt")
+        find_path(LIBXSLT_INCLUDE_DIR NAMES libxslt/xslt.h
+            PATHS "${CMAKE_OSX_SYSROOT}/usr/include"
+            PATH_SUFFIXES libxslt
+        )
         set(LIBXSLT_LIBRARIES xslt)
     endif ()
 else ()
```

**Comment by NiHoT** [comment]
I tried your patch manualy (because I built from TP5). Same error... 
No problem this is not blocking

**Comment by annulen** [comment]
Could you try this and show what is printed in line `LIBXML2_INCLUDE_DIR=`?
```diff
diff --git a/Source/cmake/OptionsQt.cmake b/Source/cmake/OptionsQt.cmake
index a4b4fa4fe60..19ab9a443e1 100644
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -340,10 +340,17 @@ else ()
 endif ()
 
 if (MACOS_FORCE_SYSTEM_XML_LIBRARIES)
-    set(LIBXML2_INCLUDE_DIR "${CMAKE_OSX_SYSROOT}/usr/include/libxml2")
+    find_path(LIBXML2_INCLUDE_DIR NAMES libxml/xpath.h
+        PATHS "${CMAKE_OSX_SYSROOT}/usr/include"
+        PATH_SUFFIXES libxml2
+    )
+    message("LIBXML2_INCLUDE_DIR=${LIBXML2_INCLUDE_DIR}")
     set(LIBXML2_LIBRARIES xml2)
+
     if (ENABLE_XSLT)
-        set(LIBXSLT_INCLUDE_DIR "${CMAKE_OSX_SYSROOT}/usr/include/libxslt")
+        find_path(LIBXSLT_INCLUDE_DIR NAMES libxslt/xslt.h
+            PATHS "${CMAKE_OSX_SYSROOT}/usr/include"
+        )
         set(LIBXSLT_LIBRARIES xslt)
     endif ()
 else ()
```

**Comment by annulen** [comment]
@NiHoT ping

**Comment by annulen** [comment]
BTW, we now have configuration with sdk 10.12 in Qt CI system, and it compiled fine there without this patch or tricks with sdk contents

**Comment by annulen** [comment]
Please reopen if there are issues with new SDKs
