### ISSUE TITLE
QWebview doesn't display JPEG on Windows/Webkit TP5/Qt5.6.2

### ISSUE THREAD

**Issue by NiHoT** [annulen/webkit#499]
Hi, after building Wekbit TP5 on windows with Qt5.6.2 and install it, I tried a quick test and I notice that JPEG img are not rendered in QWebView. Maybe a deployment issue? (PNG are ok!)

**Comment by annulen** [comment]
cc @Vitallium

**Comment by annulen** [comment]
Should be fined now, please run update-qtwebkit-win-libs again, remove Qt5WebKit.dll and relink it

**Comment by annulen** [comment]
Please reopen if it doesn't work
