### ISSUE TITLE
Random Crash relating to WTF

### ISSUE THREAD

**Issue by Zero3K** [annulen/webkit#50]
I have been having a random crash occur. A crash log generated by WinCrashReport is attached.
[webkit-crashlog.zip](https://github.com/annulen/webkit/files/201024/webkit-crashlog.zip)

**Comment by annulen** [comment]
This tracker is not intended for bugs which affect QtWebKit versions corresponding to official Qt releases. See https://github.com/annulen/webkit/wiki/Reporting-Bugs
