### ISSUE TITLE
What's the working process of this project？ 

### ISSUE THREAD

**Issue by xsren** [annulen/webkit#506]
My project is a headless browser for spider like PhantomJS. Recently I'm working on porting from QtWebKit to QtWebEngine, because QtWebKit don't support modern WEB feature . But I find it's really a hard work. Some one suggest this project. After read wiki, I think this is what I want. So I can use it to replace old QtWebkit now ?

**Comment by annulen** [comment]
Yes, many people and open source projects already do this.

**Comment by xsren** [comment]
Thank you! I will try it.
Appreciate your good job!
