### ISSUE TITLE
What is DYLD_FRAMEWORK_PATH ?

### ISSUE THREAD

**Issue by xsren** [annulen/webkit#507]
I build WebKit on my cumputer. The result:

>  WebKit is now built (23m:14s). 
 To run MiniBrowser with this newly-built code, use the
 "Tools/Scripts/run-minibrowser" script.

Then I run "Tools/Scripts/run-minibrowser" script, it says:

> Starting MiniBrowser with DYLD_FRAMEWORK_PATH set to point to built WebKit in /Users/xsren/my_projects/from_github/webkit-qtwebkit-stable/WebKitBuild/Release.
arch: /Users/xsren/my_projects/from_github/webkit-qtwebkit-stable/WebKitBuild/Release/MiniBrowser.app/Contents/MacOS/MiniBrowser isn't executable

So what is DYLD_FRAMEWORK_PATH?

My platform is MacOS 10.12.4.

**Comment by annulen** [comment]
You need to add `--qt` flag. By default on macOS script tries to start Mac port, while on *nix script asks you to specify `--gtk`, `--efl` or `--qt`, hence the confusion.

**Comment by xsren** [comment]
Thanks it worked!

**Comment by annulen** [comment]
Btw, sorry, I've forgotten to answer question in the title. Please read `man dyld`, it describes what this environment variable does, and a few others.

**Comment by xsren** [comment]
OK! Thank you!
