### ISSUE TITLE
Will this project support more Html5 feature?

### ISSUE THREAD

**Issue by xsren** [annulen/webkit#510]
I test Html5 feature support by visting http://html5test.com/ .
The result:
QtWebEngine 494
QtWebkit      336
This project   376
Chrome          519
Safri               409

So, will this project support more Html5 feature?

**Comment by annulen** [comment]
I have 388 here on Linux. Maybe your custom build does not include allfeatures. And yes, there will be more features available later.

**Comment by annulen** [comment]
My results: http://html5te.st/c1e3e53576d97a9c

**Comment by xsren** [comment]
Thank you! 
Except your great work!

**Comment by annulen** [comment]
You can paste my url and compare with your results to see table of differences

**Comment by annulen** [comment]
Also note that we probably never will have substantially higher score than contemporary version of Safari.

**Comment by xsren** [comment]
There are 4 differences:
<img width="801" alt="d1" src="https://cloud.githubusercontent.com/assets/4971925/24914999/8a319bfc-1f08-11e7-9e05-e2912c0dfc21.png">
<img width="818" alt="d2" src="https://cloud.githubusercontent.com/assets/4971925/24915000/8a356d9a-1f08-11e7-8f77-ad3dbada6773.png">
<img width="813" alt="d3" src="https://cloud.githubusercontent.com/assets/4971925/24915002/8a556514-1f08-11e7-8399-c0d1867ae7a7.png">
<img width="805" alt="d4" src="https://cloud.githubusercontent.com/assets/4971925/24915001/8a392390-1f08-11e7-81d3-4be7ca8d0435.png">

is these differences occurs because of platform difference?

**Comment by annulen** [comment]
Mostly yes. 
* Gamepad at the moment is Linux-only (though it might be possible to rewrite it with new QtGamepad module)
* WebAudio and Media Source Extensions are missing becxause we don't use AVFoundation mediaplayer on macOS, this should be possible to do without much effort

What I don't understand is missing Content Security Policy 1 in your report
