### ISSUE TITLE
Roadmap for annulen/webkit w.r.t. latest PhantomJS developments.

### ISSUE THREAD

**Issue by sowani** [annulen/webkit#516]
Hi,

I would like to know what would be the roadmap for annulen/webkit in light of PhantomJS announcement made at https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

Will that have any impact on this project?

Best regards,
Atul.

**Comment by annulen** [comment]
No, except maybe some feature priorities can change
