### ISSUE TITLE
VCPKG (informational/enhancement request)

### ISSUE THREAD

**Issue by bagong** [annulen/webkit#526]
Hi,

this is just informational, in case you shouldn't be aware of Microsofts vcpkg (on Github). So feel free to close any time. They are about to switch to qt 5.8 and offer a lovely, git based interface to a) build using MSVC and b) integrate c/c++- libraries in open source projects. If you'd add qt-webkit there, SuperCollider could be built almost entirely from that repository, which means practically no configuration work. Or to put it less Me-centric: it would give qt-webkit great exposure and potentially a large userbase. The project seems to be very active, every day new packages are added, it's overlooked by responsive MS people, pretty ideal for Windows support, I think.

**Comment by annulen** [comment]
Hi, it would be great if you or someone else provided vcpkg port. For me, it's completely out of scope, at least until QtWebKit from this repository is packaged for Debian, Fedora, and Yocto.

**Comment by bagong** [comment]
Yup, makes sense. I'll leave the issue open in case somebody else feels inspired. I'll have a look myself as soon as time permits, but this might be too difficult for me...
