### ISSUE TITLE
Windows Static Build

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#537]
Wiki documentation should detail information about how to build QtWebKit as a static library.
Required for using it in a statically linked custom PhantomJS build.

**Comment by izzyonstage** [comment]
Is there anywhere I can get info from about launching a static compilation?
I have rebuilt QtBase with static linking and now need to do the same for QtWebKit in order to use it with PhantomJS.

**Comment by annulen** [comment]
You just point CMAKE_PREFIX_PATH to Qt installation which is static, and it automatically switches to static mode

On systems with GNU ld (default on Linux) you also need to set -DUSE_THIN_ARCHIVES=OFF

**Comment by annulen** [comment]
If you get errors, look at #454, maybe it's the same issue

**Comment by annulen** [comment]
Here are configurations that @Vitallium was using: https://gist.github.com/Vitallium/c08aca68712a986254b6e6c905c1497e

**Comment by annulen** [comment]
https://github.com/annulen/webkit/wiki/Building-static-libraries
