### ISSUE TITLE
Unable to link a WebKit application: library not found for -lQt5WebKitWidgets

### ISSUE THREAD

**Issue by edgarm1964** [annulen/webkit#539]
On Mac OS X Sierra (10.11.6) and a new Qt 5.8 installation I've installed qtwebkit-tp5-qt58-darwin-x64.tar.xz by copying the contents of include, lib and mkspecs to ~/Qt/5.8/clang_64/include, .../lib and .../mkspecs.

I also downloaded the development examples (https://github.com/qt/qtwebkit-examples/archive/dev.zip) and tried to build fancybrowser. After running qmake and make, the build ends with:

```
Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -Wl,-rpath,/Users/edgarm/Qt/5.8/clang_64/lib -o fancybrowser.app/Contents/MacOS/fancybrowser .obj/main.o .obj/mainwindow.o .obj/qrc_jquery.o .obj/moc_mainwindow.o   -F/Users/edgarm/Qt/5.8/clang_64/lib -L/Users/edgarm/Qt/5.8/clang_64/lib -lQt5WebKitWidgets -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -lQt5WebKit -framework QtNetwork -framework OpenGL -framework AGL
ld: library not found for -lQt5WebKitWidgets
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fancybrowser.app/Contents/MacOS/fancybrowser] Error 1
```

When I copy the command and replace _-lQt5WebKitWidgets_ with _-framework QtWebKitWidgets_ and doing the same with _-lQt5WebKit_, it links correctly. And fancybrowser.app/Contents/MacOS/fancybrowser runs...

Within Qt Creator, I tried to build EasyKontakt (http://www.sigvdr.de/Software/EasyKontakt/EasyKontakt.html), but fails with the same error: library not found for -lQt5WebKitWidgets

Kind regards, Edgar Matzinger.

**Comment by annulen** [comment]
it was fixed in https://github.com/annulen/webkit/commit/1686903dfa4ab621a1b16a1a87529c88b07414a6

**Comment by edgarm1964** [comment]
Great! But, now I've to build the thing from source...

**Comment by annulen** [comment]
You can download snapshot build from https://0x0.st/353.zip
