### ISSUE TITLE
qtwebkit with Qt 5.8 on XP / Windows Server 2003 R2

### ISSUE THREAD

**Issue by ajankov** [annulen/webkit#550]
Is it possible to run the qtwebkit built for Qt 5.8 on XP or Windows Server 2003 R2? I get errors at runtime about missing dlls and entry points at runtime on these platforms. Thanks.

**Comment by annulen** [comment]
Qt 5.8 does not support XP. You have to use 5.6

**Comment by annulen** [comment]
Actually, my fork does not support XP officially as well, even is used with Qt 5.6, but MSYS2 project had successfully built packages that are said to be XP-compatible
