### ISSUE TITLE
CSSPropertyNames.gperf: No keywords in input file!

### ISSUE THREAD

**Issue by JoeyLi-1** [annulen/webkit#553]
Hey there,

I had encountered this error: 
4>  CSSPropertyNames.gperf: No keywords in input file!
4>  calling gperf failed: 256 at C:/cygwin/home/webkit/Source/WebCore/css/makeprop.pl line 1054.

My environment is win 10 pro/ vs2015 / qt 5.7 (with vs2017 installed as well).
Build within VS2015.

I found this (https://bugs.webkit.org/show_bug.cgi?id=140756), but seems the patch already in current code.

Who can help me out? Thank you!
@annulen @Vitallium 
Thanks,
Joey

**Comment by annulen** [comment]
Please use GnuWin32 tools from http://code.qt.io/cgit/qt/qt5.git/tree/gnuwin32/bin

**Comment by JoeyLi-1** [comment]
Switch to the tools you mentioned, but still same error:
I found in CSSPropertyNames.gperf, there is no key words at all.

> 

%}
%struct-type
struct Property;
%omit-struct-type
%language=C++
%readonly-tables
%global-table
%compare-strncmp
%define class-name CSSPropertyNamesHash
%define lookup-function-name findPropertyImpl
%define hash-function-name propery_hash_function
%define word-array-name property_wordlist
%enum
%%
%%
const Property* findProperty(const char* str, unsigned int len)
{
    return CSSPropertyNamesHash::findPropertyImpl(str, len);
}

I am investigating why this return an empty array.
> my @NAMES = applyPreprocessor("CSSPropertyNames.in", $defines, $preprocessor);
(in source/webcore/css/makeprop.pl)


Do you have any experience about this?

**Comment by annulen** [comment]
Did you do clean build after changing path to utilities?

**Comment by JoeyLi-1** [comment]
Just rebuild. Same error!

Step 1: with Cygwin bash
joey@DESKTOP-484MB9B /home/webkit
$ ./Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=\"C:\Qt\5.7\msvc2015\" -G \"Visual Studio 14 2015\""

Step 2: Build WebKit.sln within vs2015

My environment: 
Path=C:\Python27\;C:\Python27\Scripts\;C:\Perl64\site\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Git LFS;C:\Perl64\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\CMake\bin;C:\Ruby23-x64\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Ruby23-x64\bin;C:\Python27;C:\Users\joey\AppData\Local\Microsoft\WindowsApps;C:\Users\joey\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Python27\Scripts;C:\Perl64\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Tools\ninja-win\
WEBKIT_LIBRARIES=C:\cygwin\home\webkit\WebKitLibraries\win
WEBKIT_OUTPUTDIR=C:\Code\GitHub\webkit-output

**Comment by bagong** [comment]
https://gist.github.com/bagong/82a36c6f905c1143f73037fb495bb701

This is what it looks for me with latest qtwebkit, VS2017, gperf from Qt5 source and libraries from vcpkg.

I once got a gperf related error that went away after I added it to the path.

**Comment by JoeyLi-1** [comment]
I found $1 is empty in (C:\cygwin\home\webkit\Source\WebCore\bindings\scripts\preprocessor.pm)
chomp(my $preprocessor = `cygpath -u '$1'`) if (defined $1);

So I comment out this line and this error gone. 
Still have other errors, go on to fix them. 

Thank you for your help! @annulen @bagong .

**Comment by annulen** [comment]
o_O why are you using cygwin? I think this is the root of the problem, as it was never tested

**Comment by JoeyLi-1** [comment]
Oops! I had encountered the issue "miss features.h" so I change to cygwin though it is wired.
I will try to build it again on window later. Maybe thing will get better as you said "it is the root of the problem"

**Comment by annulen** [comment]
<features.h> is checked in configure time and is needed only on platforms that use glibc
