### ISSUE TITLE
Error	C2668	'WebCore::IDBServer::UniqueIDBDatabase::storeCallback': ambiguous call to overloaded function	WebCore (WebCore\WebCore)	C:\Code\GitHub\webkit\Source\WebCore\Modules\indexeddb\server\UniqueIDBDatabase.cpp	1185

### ISSUE THREAD

**Issue by JoeyLi-1** [annulen/webkit#555]
Does anyone encounter this issue before?
Any idea about how to fix it? Thanks!

@annulen I had removed cygwin environment. U are right. Thank you!

**Comment by JoeyLi-1** [comment]
Found this: https://bugs.webkit.org/show_bug.cgi?id=157192
Upgrade to VS2015 update 3. 
Solved.

**Comment by JoeyLi-1** [comment]
Sorry, the error still exist. Who can help me? @bagong?

**Comment by annulen** [comment]
Are you sure you are using upgraded compiler? e.g. maybe reboot is needed

**Comment by JoeyLi-1** [comment]
Trust me!
![image](https://cloud.githubusercontent.com/assets/20162464/26487212/1d4bacde-4231-11e7-93c4-19ed21ad87e3.png)
I just use a workaround:
 auto callback = [this, self, refTransaction](const IDBError& error) {
to
ErrorCallback callback = [this, self, refTransaction](const IDBError& error) {
And I will try to compile the original code again after reboot later.

**Comment by annulen** [comment]
Nobody else have reported this problem so far

**Comment by bagong** [comment]
Sorry @JoeyLi-1 , I've never seen this. But I've only been using VS2017...

**Comment by JoeyLi-1** [comment]
Yeah! Build success!
VS2015 has such issue;
VS2015 update 3 -> same issue;
Reboot & rebuild -> same issue;
Use VS2017 upgrade toolset to 141 and win sdk 10.0.14393.0. -> success.
I don`t know why. Maybe environment issue.
And I encountered this issue as well (https://github.com/annulen/webkit/issues/432) which does not work under VS2015. But VS2017 solve all the issues.
Thanks for your help! @annulen @bagong
