### ISSUE TITLE
Static linked webkit build issue

### ISSUE THREAD

**Issue by JoeyLi-1** [annulen/webkit#557]
Hi @annulen,
I had build static linked QT but I encountered some new errors like this:
2>------ Build started: Project: QtTestBrowser, Configuration: Release Win32 ------
2>libpng.lib(pngpread.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
2>libpng.lib(png.obj) : error LNK2005: _png_sRGB_table already defined in Qt5Gui.lib(png.obj)
2>libpng.lib(png.obj) : error LNK2005: _png_sRGB_delta already defined in Qt5Gui.lib(png.obj)
2>libpng.lib(png.obj) : error LNK2005: _png_sRGB_base already defined in Qt5Gui.lib(png.obj)
2>libpng.lib(png.obj) : error LNK2005: _png_image_error already defined in Qt5Gui.lib(png.obj)
2>libpng.lib(png.obj) : error LNK2005: _png_image_free already defined in Qt5Gui.lib(png.obj)
2>libpng.lib(png.obj) : error LNK2005: _png_set_option already defined in Qt5Gui.lib(png.obj)

I already update related libs mentioned in #432.
Do you have any idea about how to fix this?

Thanks,
Joey

**Comment by JoeyLi-1** [comment]
Build webkit: perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=\"C:\Qt\static\5.7.0\" -G \"Visual Studio 14 2015\""

Build QT: configure.bat -static -release -platform win32-msvc2015 -prefix C:\Qt\Static\5.7.0\ -qt-zlib -qt-pcre -qt-libpng -qt-libjpeg -qt-freetype -opengl desktop -qt-sql-sqlite -no-openssl -opensource -confirm-license -make libs -nomake tools -nomake examples -nomake tests

**Comment by annulen** [comment]
Error happens because Qt5Gui.lib already includes libpng. You should disable libpng in Qt configuration (as well as libjpeg and zlib, and you can do same for sqlite too)

**Comment by JoeyLi-1** [comment]
@annulen you are right. But I met new issues.

> 13>Qt5MultimediaWidgets.lib(qpaintervideosurface.obj) : error LNK2019: unresolved external symbol "public: void (__cdecl*__thiscall QGLContext::getProcAddress

I guess still something wrong with my static QT build.

Could you please help to review these QT config params for me?
configure.bat -static -release -platform win32-msvc2015 -prefix C:\Qt\Static\5.7.0\ -qt-pcre -no-libpng -no-libjpeg -qt-freetype -opengl desktop -no-sql-sqlite -openssl -opensource -confirm-license -make libs -nomake tools -nomake examples -nomake tests

Is is correct or enough for me to build QT? It took me hours to start over and over again. Nightmare.

Thanks, 
Joey

**Comment by bagong** [comment]
Yea, it's a nightmare :smile:

**Comment by JoeyLi-1** [comment]
@bagong Can you share your configure param list with me?

**Comment by bagong** [comment]
@JoeyLi-1 , I have sofar not dared to try static linking, although we actually also might have a use case for it (subtle differences in Linux distros). I've seen it's a headache for almost everybody, and the resulting binaries are gigantic... So my builds are simple, everything just default (including Qt and dependencies). The only variation I have is switching between Qt-media and media-foundation, that switch seems not to cause any trouble.
As to my comment, I was just empathizing. If you don't have a dedicated build machine and are good at mental multi-tasking it is nightmare with these monster packages ;)

**Comment by annulen** [comment]
@JoeyLi-1 `-opengl desktop` is probably the culprit, try `-no-opengl` instead.

@Vitallium Could you share your Qt configure parameters on Windows?

**Comment by Vitallium** [comment]
Sure, here is my configuration:

```
configure -static -static-runtime -nomake examples -nomake tests -nomake tools -system-zlib -system-libpng -system-libjpeg -opensource -no-cups -confirm-license -no-sql-psql -qt-pcre -no-evdev -no-qml-debug -no-opengl -openssl -openssl-linked -no-icu -prefix %CD%\..\qtbase-build
```

**Comment by JoeyLi-1** [comment]
Thank you @annulen @Vitallium , The Webkit is built successfully. I met I think which is the last error when I build phantomJS:

> libWTF.lib(WTFString.obj):-1: error: LNK2001: unresolved external symbol _u_charDirection_57

This error popup in qt creator. Lots of them(over 230). Any suggestions to get rid of this?

BTW, I had to change the configure param list a little bit:

> configure.bat -static -release -platform win32-msvc2015 -prefix C:\Qt\Static\5.7-msvc\ -qt-pcre -no-libpng -no-libjpeg -qt-freetype -opengl desktop -no-sql-sqlite -openssl -I C:\openssl\include\ -L C:\openssl\lib\ -opensource -confirm-license -make libs -nomake tools -nomake examples -nomake tests -no-cups -no-evdev -no-qml-debug

> perl Tools/Scripts/build-webkit --qt --release --only-webkit --no-device-orientation --no-web-audio --no-video --no-video-track --no-touch-events --no-touch-slider --no-geolocation --no-xslt --no-netscape-plugin-api --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=\"C:\Qt\static\5.7-msvc\" -G \"Visual Studio 14 2015\""

And I had copy all the .lib files from \webkit\WebKitLibraries\win to qt static build folder and rename webcore to libwebcore as well.

**Comment by JoeyLi-1** [comment]
@annulen  @Vitallium 
I solved this issue by add LIBS in phantomjs.pro.
And I summarized what I did here (https://github.com/ariya/phantomjs/issues/15018) hope it could help others. Again, thank you very much for your help! :)
