### ISSUE TITLE
Can't Compile Alpha2

### ISSUE THREAD

**Issue by jeprojects** [annulen/webkit#572]
Please delete this.

**Comment by annulen** [comment]
Are you building on Windows? Instruction says:

>You also need to clone http://code.qt.io/cgit/qt/qt5.git and add gnuwin32/bin from cloned repository into %PATH%

**Comment by jeprojects** [comment]
Yeah, strange thing.. I had the environment all setup as I compiled alpha 1.. But after a windows update I lost my environment variables :(
