### ISSUE TITLE
cmake generates incorrect .pc files

### ISSUE THREAD

**Issue by antonio-rojas** [annulen/webkit#576]
From the downstream report https://bugs.archlinux.org/task/54577 :

Errors in Qt5WebKit.pc and Qt5WebKitWidgets.pc in qt5-webkit-5.212.0alpha2-1-x86_64:

1) Both are missing the Description field. For example, pkg-config --validate Qt5WebKit reports a missing Description field. pkg-config --exists Qt5WebKit fails with error code. Consequently, builds of dependent packages fail.

2) Qt5WebKit.pc contains Cflags: -I/usr/include/qt/Qt5WebKit. That directory doesn't exist. It should be Cflags: -I/usr/include/qt/QtWebKit

2) Qt5WebKitWidgets.pc contains Cflags: -I/usr/include/qt/Qt5WebKitWidgets. That directory doesn't exist. It should be Cflags: -I/usr/include/qt/QtWebKitWidgets

**Comment by annulen** [comment]
Will be fixed when remainder of #388 is merged

**Comment by mitya57** [comment]
1) was fixed in 0325d51c4a2a05fb, 2) and 3) were just merged with #735. I guess you can close this bug now.
