### ISSUE TITLE
MediaPlayerPrivate... Errors In Build MSVC2015

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#580]
I have just got the latest qtwebkit-stable commits.
When I try to build this it is failing with the following errors:
[https://pastebin.com/p1hTjpUK](https://pastebin.com/p1hTjpUK)

Any idea how to fix this or avoid it?

**Comment by annulen** [comment]
Are you building with disabled video?

**Comment by izzyonstage** [comment]
yes

**Comment by annulen** [comment]
Change USE_MEDIA_FOUNDATION to OFF in CMakeCache.txt and rebuild (you can use cmake-gui or ccache as well). I forgot to add automagic for this

**Comment by annulen** [comment]
Whoops, typed ccace instead of ccmake :)

**Comment by izzyonstage** [comment]
I have used -DUSE_MEDIA_FOUNDATION=OFF in the cmake command and that seems to get further. Just checking build errors as these may now be something else.

**Comment by annulen** [comment]
BTW, you should use qtwebkit-5.212 branch instead of qtwebkit-stable. While qtwebkit-stable should work fine, qtwebkit-5.212 contains lots of backported patches from WebKit trunk that fix bugs and security issues.

**Comment by annulen** [comment]
See ReadMe.md for explanation of branches

**Comment by izzyonstage** [comment]
The errors I am now getting are:
[https://pastebin.com/VKuC9ZK6](https://pastebin.com/VKuC9ZK6)

Not sure if this is related. But looking at this it seems WebKit2 is being built.
How can I disable this? or is this now just how it is?

**Comment by izzyonstage** [comment]
> BTW, you should use qtwebkit-5.212 branch instead of qtwebkit-stable

I am now indeed using this branch

**Comment by annulen** [comment]
* Building WebKit2 on Windows with ICU 59.1 is supported only in qtwebkit-5.212
* You can use -DENABLE_WEBKIT2=OFF to disable WebKit 2

**Comment by annulen** [comment]
* Building WebKit2 is not supported without ENABLE_OPENGL, next versions will error out in this case

**Comment by izzyonstage** [comment]
> Building WebKit2 is not supported without ENABLE_OPENGL

I currently build Qt with `-opengl desktop` option, should this work if I set `-DENABLE_OPENGL=ON`?

**Comment by annulen** [comment]
If you are building specifically for PhatomJS you should really use -DENABLE_WEBKIT2=OFF

Otherwise yes

**Comment by izzyonstage** [comment]
Great stuff.
I am indeed building for PhantomJS so will disable WebKit2 for now.

**Comment by annulen** [comment]
Actually, I'll disable WebKit 2 for static builds entirely. It doesn't make much sense without changing way how auxiliary processes are built/linked.

**Comment by jeprojects** [comment]
@izzyonstage Just out of interest, what are commands are you using for disabling stuff for use with PhantomJS.

**Comment by Vitallium** [comment]
Official build commands are: 

**Windows:**
```
perl f:/development/webkit/Tools/Scripts/build-webkit --release --64-bit --qt --no-geolocation --no-device-orientation --no-video --no-video-track --no-netscape-plugin-api --no-touch-events --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=f:\dev\qtbase-build -DUSE_QT_MULTIMEDIA=OFF -DENABLE_API_TESTS=OFF -DENABLE_TOOLS=OFF -DUSE_STATIC_RUNTIME=ON -DENABLE_OPENGL=OFF -DENABLE_WEBKIT2=OFF -DUSE_MEDIA_FOUNDATION=OFF "
```

**Linux:**
```
./Tools/Scripts/build-webkit --qt --release --no-device-orientation \
--no-web-audio --no-video --no-video-track --no-touch-events \
--no-touch-slider --no-geolocation --64-bit \
--cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=/mnt/dev/qtbase-build -DENABLE_NETSCAPE_PLUGIN_API=OFF -DUSE_GSTREAMER=OFF -DUSE_THIN_ARCHIVES=OFF -DENABLE_API_TESTS=OFF -DENABLE_TEST_SUPPORT=OFF -DENABLE_TOOLS=OFF -DENABLE_OPENGL=OFF -DENABLE_WEBKIT2=OFF"
```

**Comment by izzyonstage** [comment]
due to the fact we have some custom changes on-top of this, we currently do not use the build-webkit script and I am calling the relevant commands directly.
e.g.
```
cmake {pretty much everything in cmakeargs with the extras that would have been added by the script}
jom install
```

**Comment by annulen** [comment]
There is another possible approach to static build: build qtwebkit as a submodule of qt5. In this case it's possible to reuse the same libjpeg, libpng, zlib, sqlite that Qt uses, and also do some automatic configuration based on Qt's configure options

**Comment by izzyonstage** [comment]
> build qtwebkit as a submodule of qt5

that would be good. how would I do that?

Currently I am building as static build but not with /MT (static runtime; but this will be required later when I get everything else working).
Since the extra addition it is now building but still having other problems when trying to use it from PhantomJS (already tracked in another issue).

**Comment by annulen** [comment]
>how would I do that?

* You need to get `qtwebkit` source directory inside base directory of `qt5`, i.e. on the same level as `qtbase`. If you use git, you just add submodule qtwebkit and switch to `5.212` branch, otherwise you need to unpack source targball there and make sure directory is named `qtwebkit`, you should have `qtwebkit/Source` and `qtwebkit/Tools`
* Then you run configure in Qt just like you usually do it. QtWebKit module will be built.

Caveats:
* I don't know if it's possible to pass qmake arguments via configure, so I don't yet know how to pass your configuration to QtWebKit. Maybe it will require adding configure.json to QtWebKit so you can use new configuration system of Qt. I can ask ossi|tt if you don't have answers
* `-static-runtime` flag of `configure` should work, i.e. `/MT` will be used if it's present and `/MD` otherwise. However, I doubt that anyone has ever tried this build method with static build so there may be dragons. I probably need to try it out myself first, to ensure that it works at least on Linux.

**Comment by annulen** [comment]
* When building this way, `jom` will be used automagically, no need to change generator
