### ISSUE TITLE
QtWebNetworkProcess - link error

### ISSUE THREAD

**Issue by tjelbert** [annulen/webkit#583]
building 5.212.0-alpha2 tarball

[5221/5257] Linking CXX executable bin/QtWebNetworkProcess
FAILED: bin/QtWebNetworkProcess
: && /var/lib/sorcery/build/c++  -march=native -mtune=native -m64 -pipe -ffast-math -funroll-loops -fno-exceptions -fno-strict-aliasing -fno-rtti -std=c++11 -Wno-expansion-to-defined -march=native -mtune=native -m64 -pipe -ffast-math -funroll-loops -ffunction-sections -fdata-sections  -Wl,--as-needed -Wl,--as-needed   -rdynamic Source/WebKit2/CMakeFiles/NetworkProcess.dir/NetworkProcess/EntryPoint/qt/NetworkProcessMain.cpp.o  -o bin/QtWebNetworkProcess  -Wl,-rpath,/usr/src/qtwebkit-5.212.0-alpha2/build/lib:/opt/qt5/lib: lib/libQt5WebKit.so.5.212.0 /opt/qt5/lib/libQt5Gui.so.5.9.0 /opt/qt5/lib/libQt5Network.so.5.9.0 /opt/qt5/lib/libQt5Core.so.5.9.0 -Wl,-rpath-link,/usr/src/qtwebkit-5.212.0-alpha2/build/lib:/opt/qt5/lib && :
Source/WebKit2/CMakeFiles/NetworkProcess.dir/NetworkProcess/EntryPoint/qt/NetworkProcessMain.cpp.o: In function `main':
NetworkProcessMain.cpp:(.text.main+0x1c): undefined reference to `WebKit::NetworkProcessMainQt(int, char**)'
collect2: error: ld returned 1 exit status
[5222/5257] Building CXX object Source/WebKit2/CMakeFiles/DatabaseProcess.dir/DatabaseProcess/EntryPoint/

**Comment by tjelbert** [comment]
-- Enabled features:
--  ENABLE_ACCELERATED_2D_CANVAS ............ ON
--  ENABLE_ALLINONE_BUILD                     0
--  ENABLE_API_TESTS ........................ 0
--  ENABLE_CSS_GRID_LAYOUT                    ON
--  ENABLE_DATABASE_PROCESS ................. ON
--  ENABLE_DATALIST_ELEMENT                   ON
--  ENABLE_DEVICE_ORIENTATION ............... 0
--  ENABLE_DRAG_SUPPORT                       ON
--  ENABLE_FULLSCREEN_API ................... ON
--  ENABLE_GAMEPAD_DEPRECATED                 0
--  ENABLE_GEOLOCATION ...................... 0
--  ENABLE_ICONDATABASE                       ON
--  ENABLE_INDEXED_DATABASE ................. ON
--  ENABLE_INSPECTOR_UI                       ON
--  ENABLE_JIT .............................. ON
--  ENABLE_LEGACY_WEB_AUDIO                   ON
--  ENABLE_LINK_PREFETCH .................... ON
--  ENABLE_MEDIA_SOURCE                       ON
--  ENABLE_NETSCAPE_PLUGIN_API .............. ON
--  ENABLE_OPENGL                             ON
--  ENABLE_PRINT_SUPPORT .................... ON
--  ENABLE_QT_GESTURE_EVENTS                  ON
--  ENABLE_QT_WEBCHANNEL .................... ON
--  ENABLE_SAMPLING_PROFILER                  0
--  ENABLE_SPELLCHECK ....................... ON
--  ENABLE_TOUCH_EVENTS                       0
--  ENABLE_VIDEO ............................ ON
--  ENABLE_WEBKIT2                            ON
--  ENABLE_WEB_AUDIO ........................ ON
--  ENABLE_X11_TARGET                         ON
--  ENABLE_XSLT ............................. ON
--  USE_GSTREAMER                             1
--  USE_LIBHYPHEN ........................... 0
--  USE_MEDIA_FOUNDATION                      OFF
--  USE_QT_MULTIMEDIA ....................... OFF
--  USE_SYSTEM_MALLOC                         1
--  USE_WOFF2 ............................... ON
-- Configuring done

**Comment by annulen** [comment]
Do you have other version of QtWebKit installed in Qt prefix? You have to uninstall it before building

**Comment by tjelbert** [comment]
no


$ ag qtweb /var/state/sorcery/packages
550:qtwebsockets:20170531:installed:5.9.0
551:qtwebchannel:20170531:installed:5.9.0
552:qtwebengine:20170531:installed:5.9.0

**Comment by tjelbert** [comment]
full compile log 


[webkitqt-5.212.0-alpha2.zip](https://github.com/annulen/webkit/files/1112524/webkitqt-5.212.0-alpha2.zip)

**Comment by annulen** [comment]
Side note: I see you use `-funroll-loops`, I wouldn't do it without benchmarking

**Comment by annulen** [comment]
What does `objdump -tT libQt5WebKit.so.5 | grep NetworkProcessMainQt` show?

**Comment by tjelbert** [comment]
nothing

root@Horos:/usr/src/qtwebkit-5.212.0-alpha2/build/lib# objdump -tT libQt5WebKit.so.5 | grep NetworkProcessMainQt
root@Horos:/usr/src/qtwebkit-5.212.0-alpha2/build/lib#

**Comment by annulen** [comment]
Is Qt built with `reduce_exports` feature (see $QTROOT/mkspecs/qconfig.pri)? If no, Q_DECL_EXPORT is empty and that breaks the show

**Comment by annulen** [comment]
Note tha reduce_exports is default option, but depends on configure-time test that may fail for bogus reason

**Comment by tjelbert** [comment]
QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT.global.enabled_features = shared c++11 c++14 c++1z concurrent pkg-config
QT.global.disabled_features = cross_compile framework rpath appstore-compliant debug_and_release simulator_and_device build_all force_asserts separate_debug_info static
QT_CONFIG += shared release c++11 c++14 c++1z concurrent dbus mremap reduce_exports reduce_relocations stl
CONFIG += shared release
QT_VERSION = 5.9.0
QT_MAJOR_VERSION = 5
QT_MINOR_VERSION = 9
QT_PATCH_VERSION = 0
QT_EDITION = OpenSource

**Comment by annulen** [comment]
Arrgh

Could you get preprocessed source for NetworkProcessMainQt.cpp and look if `int NetworkProcessMainQt(int argc, char** argv)` has visibility attribute in place?

**Comment by annulen** [comment]
Also, output of `find . -name NetworkProcessMainQt.cpp.o -exec objdump -tT {} \; | grep NetworkProcessMainQt`  in your build dir would be interesting

**Comment by tjelbert** [comment]
# find . -name NetworkProcessMainQt.cpp.o -exec objdump -tT {} \; | grep NetworkProcessMainQt
objdump: ./Source/WebKit2/CMakeFiles/WebKit2.dir/NetworkProcess/qt/NetworkProcessMainQt.cpp.o: not a dynamic object
./Source/WebKit2/CMakeFiles/WebKit2.dir/NetworkProcess/qt/NetworkProcessMainQt.cpp.o:     file format elf64-x86-64
0000000000000000 l    df *ABS*  0000000000000000 NetworkProcessMainQt.cpp
0000000000000000 l    d  .text._ZN6WebKit20NetworkProcessMainQtEiPPc    0000000000000000 .text._ZN6WebKit20NetworkProcessMainQtEiPPc
0000000000000000 g     F .text._ZN6WebKit20NetworkProcessMainQtEiPPc    0000000000000051 _ZN6WebKit20NetworkProcessMainQtEiPPc

**Comment by annulen** [comment]
Heh, object file is correct

**Comment by annulen** [comment]
Need to see full command line of libQt5WebKit.so.5.212.0 linking (remove the file and run ninja -v)

If you run ninja -k 1000 after that, are there any other different missing symbols? Can QtTestBrowser be linked?

**Comment by annulen** [comment]
Hmm, why `-fvisibility=hidden -fvisibility-inlines-hidden` are missing in CXXFLAGS? Are you doing something nasty?

**Comment by tjelbert** [comment]
[XX.zip](https://github.com/annulen/webkit/files/1112882/XX.zip)

**Comment by tjelbert** [comment]
not aware of anything nasty

**Comment by annulen** [comment]
You have `--as-needed` in your linker invocation. This is probably the culprit

>not aware of anything nasty

Your compilation and linking flag are very different from default. No visibility flags, as-needed, maybe something else

**Comment by annulen** [comment]
Please reopen if you still experience this issue
