### ISSUE TITLE
WebCore does not statically include zlib

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#585]
Building QtWebKit as a static library with MSVC2015 causes issues at end of build.
When it gets to linking DumpRenderTree there are unresolved external symbols.

Should WebCore include this dependency publicly? or should DumpRenderTree also include it in it's LIBRARIES list?

[https://pastebin.com/mNGG28vt](https://pastebin.com/mNGG28vt)

**Comment by annulen** [comment]
DumpRenderTree is built only when ENABLE_TEST_SUPPORT=ON. I don't think it makes much sense to support this configuration for static build, and you certainly should make it OFF for production

**Comment by izzyonstage** [comment]
I have set that to off, but it's still building both QtTestBrowser and DumpRenderTree.

**Comment by izzyonstage** [comment]
Have just re-checked my build script and it had a typo in. just running a new build now and will close this issue if it succeeds.

**Comment by izzyonstage** [comment]
Build still seems to fail even though I have fixed the typo for `-DENABLE_TEST_SUPPORT=OFF`.

**Comment by izzyonstage** [comment]
Just checkec the OptionsQt.cmak file and it looks like it might be because I had `-DDEVELOPER_MODE=ON` I have changed this to be off and running a new build now.

**Comment by izzyonstage** [comment]
Build just finished and it still failed.
There does not seem to be any way to stop QtWebBrowser from compiling at all.

**Comment by annulen** [comment]
That's correct, QtTestBrowser is always compiled

**Comment by izzyonstage** [comment]
I think that might need some changes to work then as I currently get issues with unresolved external symbols for zlib.
[https://pastebin.com/6Q8TNTPv](https://pastebin.com/6Q8TNTPv)
Is there a cmake file somewhere that I can add this dependency to for MSVC builds?

**Comment by izzyonstage** [comment]
Think I may have a fix for this already.
I had removed the addition of zlib into the `EXTRA_LIBS_NAMES` variable.
Just running a new build to test this.
This may also be the same fix needed to get DumpRenderTree to build also.

**Comment by annulen** [comment]
EXTRA_LIBS_NAMES affects only .pri files generated for qmake

For cmake targets, either ${ZLIB_LIBRARIES} should be added explicitly to QtTestBrowser, or it should be added with target_link_libraries(... PUBLIC ${ZLIB_LIBRARIES}) to Source/WebKit/CMakeLists.txt

**Comment by izzyonstage** [comment]
I believe it should be in the .pri file as it is a dependency required when using WebCore.
So in WebKit if you add the ${ZLIB_LIBRARIES} to there then all the includes pull through and QtTestBrowser should get the additional includes automatically.
After all it is WebCore that uses zlib, so surely it should be the first Qt Module that should define this requirement?
I could be wrong, but that was my reasoning.

**Comment by izzyonstage** [comment]
> target_link_libraries(... PUBLIC ${ZLIB_LIBRARIES}) to Source/WebKit/CMakeLists.txt

I can try this, but was not sure if that might affect anything else?

**Comment by annulen** [comment]
```diff
diff --git a/Source/WebKit/CMakeLists.txt b/Source/WebKit/CMakeLists.txt
index 82dc1e662a5..dcc6b73bbaa 100644
--- a/Source/WebKit/CMakeLists.txt
+++ b/Source/WebKit/CMakeLists.txt
@@ -75,6 +75,10 @@ if (${PORT} STREQUAL "Qt")
         )
     endif ()

+    if (QT_STATIC_BUILD)
+        # link all transitive libraries here
+    endif ()
+
     if (ENABLE_WEBKIT2)
         add_dependencies(WebKit WebKit2)
     endif ()
```

**Comment by izzyonstage** [comment]
As it is actually WebCore that has the dependency should it not go in Source/WebCore/CMakeLists.txt?

**Comment by izzyonstage** [comment]
And possibly just be added to the `${WebCore_LIBRARIES}` list?

**Comment by izzyonstage** [comment]
Also would this be a global Qt port thing to do or just for MSVC do you think?

**Comment by annulen** [comment]
> As it is actually WebCore that has the dependency should it not go in Source/WebCore/CMakeLists.txt? And possibly just be added to the ${WebCore_LIBRARIES} list?

These libraries are already in that list. Problem is that they are linked with implicit `PRIVATE`

>Also would this be a global Qt port thing to do or just for MSVC do you think?

It's about static build, not compiler

**Comment by izzyonstage** [comment]
@annulen - That change did not fix my build issue. I still have the same errors.
I am trying a few other possible options, so will see how they go.

**Comment by annulen** [comment]
Replaced with #695
