### ISSUE TITLE
Does not correctly query for QT_OPENGL_ES_2

### ISSUE THREAD

**Issue by Vogtinator** [annulen/webkit#598]
Building with an GLESv2 enabled Qt >= 5.8 does not work as expected, as https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/WTF/wtf/Platform.h#L1060 is not enough to get the config of QtGui, such as ```QT_OPENGL_ES_2```.
Replacing the
```#include <qglobal.h>```
with
```#include <QtGui/QWindow>```

makes it build again.

**Comment by mitya57** [comment]
I can confirm this. `QT_OPENGL_ES_2` is defined in `QtGui/qtgui-config.h` for me, which is not included by `QtCore/qglobal.h`.

**Comment by SevereOverfl0w** [comment]
Replacing `<qglobal.h>` with `<QtGui/QWindow>` seemed to cause this error on x86_64: https://travis-ci.org/voidlinux/void-packages/jobs/279150998

The other architectures seemed fine though.

**Comment by annulen** [comment]
Should be fixed after 8fd4477 and 7ec8dd4
