### ISSUE TITLE
WK2 build failure: CMake does not add QtQuick private header include path

### ISSUE THREAD

**Issue by lachs0r** [annulen/webkit#599]
In `Source/WebKit2/PlatformQt.cmake`, `Qt5Quick_PRIVATE_INCLUDE_DIRS` is `/usr/include/qt5/QtNetwork/5.9.1/usr/include/qt5/QtNetwork/5.9.1/QtNetwork/usr/include/qt5/QtCore/5.9.1/usr/include/qt5/QtCore/5.9.1/QtCore/usr/include/qt5/QtGui/5.9.1/usr/include/qt5/QtGui/5.9.1/QtGui` on my system. This does not contain the QtQuick directory even though the private headers are definitely installed in the correct location. This results in compilation failure of `Source/WebKit2/UIProcess/API/qt/qquicknetworkreply.cpp`:

```
In file included from ../Source/WebKit2/UIProcess/API/qt/qquicknetworkreply_p.h:27:0,
                 from ../Source/WebKit2/UIProcess/API/qt/qquicknetworkreply.cpp:22:
../Source/WebKit2/UIProcess/API/qt/qquickwebview_p.h:29:10: fatal error: private/qquickflickable_p.h: No such file or directory
 #include <private/qquickflickable_p.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by annulen** [comment]
That's an issue with your Qt installation. See https://bugreports.qt.io/browse/QTBUG-37417

Quick workaround is to edit your `Qt5QuickConfig.cmake` and set proper value in `Qt5Quick_PRIVATE_INCLUDE_DIRS`

**Comment by annulen** [comment]
* If your Qt is provided by distro, report to them that Qt5Quick_PRIVATE_INCLUDE_DIRS is not set and advise to avoid using out-of-tree build when building qtdeclarative
* If you build Qt yourself, use in-source build or build from git repository
