### ISSUE TITLE
Cross Compile error Qt5.9.1

### ISSUE THREAD

**Issue by schoeffi91** [annulen/webkit#601]
Hi, when i try to cross compile the 5.212 qtwebkit i get the following error in WebCore during the build: 
QtVersion is 5.9.1

```
latform/graphics/opengl/GraphicsContext3DOpenGLES.cpp: In member function ‘bool WebCore::GraphicsContext3D::reshapeFBOs(const WebCore::IntSize&)’:
platform/graphics/opengl/GraphicsContext3DOpenGLES.cpp:113:90: error: invalid static_cast from type ‘WebCore::Extensions3D*’ to type ‘WebCore::Extensions3DOpenGLES*’
     Extensions3DOpenGLES* extensions = static_cast<Extensions3DOpenGLES*>(getExtensions());
                                                                                          ^
platform/graphics/opengl/GraphicsContext3DOpenGLES.cpp:114:19: error: invalid use of incomplete type ‘class WebCore::Extensions3DOpenGLES’
     if (extensions->isImagination() && m_attrs.antialias) {
                   ^~
In file included from platform/graphics/opengl/GraphicsContext3DOpenGLES.cpp:33:0:
platform/graphics/GraphicsContext3D.h:100:7: note: forward declaration of ‘class WebCore::Extensions3DOpenGLES’
 class Extensions3DOpenGLES;
       ^~~~~~~~~~~~~~~~~~~~

```
Knows someone a solution for the problem?
The original webkit builds without errors.

**Comment by annulen** [comment]
Please try this patch

```diff
diff --git a/Source/WebCore/platform/graphics/opengl/TemporaryOpenGLSetting.cpp b/Source/WebCore/platform/graphics/opengl/TemporaryOpenGLSetting.cpp
index c502a0c3b95..8ae96b94ce8 100644
--- a/Source/WebCore/platform/graphics/opengl/TemporaryOpenGLSetting.cpp
+++ b/Source/WebCore/platform/graphics/opengl/TemporaryOpenGLSetting.cpp
@@ -29,7 +29,11 @@
 #if ENABLE(GRAPHICS_CONTEXT_3D)
 #include "TemporaryOpenGLSetting.h"
 
-#if USE(OPENGL_ES_2)
+#if PLATFORM(QT)
+#define FUNCTIONS m_functions
+#include "OpenGLShimsQt.h"
+#define glIsEnabled(...) m_functions->glIsEnabled(__VA_ARGS__)
+#elif USE(OPENGL_ES_2)
 #include <GLES2/gl2.h>
 #include "OpenGLESShims.h"
 #elif PLATFORM(IOS)
@@ -38,10 +42,6 @@
 #include <OpenGL/gl.h>
 #elif PLATFORM(GTK) || PLATFORM(EFL) || PLATFORM(WIN)
 #include "OpenGLShims.h"
-#elif PLATFORM(QT)
-#define FUNCTIONS m_functions
-#include "OpenGLShimsQt.h"
-#define glIsEnabled(...) m_functions->glIsEnabled(__VA_ARGS__)
 #endif
 
 namespace WebCore {
diff --git a/Source/WTF/wtf/Platform.h b/Source/WTF/wtf/Platform.h
index f3d72521721..0666ac710fa 100644
--- a/Source/WTF/wtf/Platform.h
+++ b/Source/WTF/wtf/Platform.h
@@ -1052,6 +1052,9 @@
 #if PLATFORM(QT)
 #ifdef __cplusplus
 #include <qglobal.h>
+#if QT_VERSION >= QT_VERSION_CHECK(5,8,0)
+#include <QtGui/qtguiglobal.h>
+#endif
 #endif
 #if defined(QT_OPENGL_ES_2) && !defined(USE_OPENGL_ES_2)
 #define USE_OPENGL_ES_2 1
```

**Comment by schoeffi91** [comment]
Thank you very much for your patch. I builds now!

Now i get an linker error:

`
GraphicsContext3DOpenGLES.cpp:(.text._ZN7WebCore17GraphicsContext3D11reshapeFBOsERKNS_7IntSizeE+0x370): undefined reference to `glRenderbufferStorage'
GraphicsContext3DOpenGLES.cpp:(.text._ZN7WebCore17GraphicsContext3D11reshapeFBOsERKNS_7IntSizeE+0x384): undefined reference to `glFramebufferRenderbuffer'
GraphicsContext3DOpenGLES.cpp:(.text._ZN7WebCore17GraphicsContext3D11reshapeFBOsERKNS_7IntSizeE+0x39c): undefined reference to `glBindRenderbuffer'
GraphicsContext3DOpenGLES.cpp:(.text._ZN7WebCore17GraphicsContext3D11reshapeFBOsERKNS_7IntSizeE+0x3b0): undefined reference to `glRenderbufferStorage'
../../lib/../Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/opengl/Extensions3DOpenGLES.cpp.o: In function `WebCore::Extensions3DOpenGLES::getExtensions()':
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES13getExtensionsEv+0xc): undefined reference to `glGetString'
../../lib/../Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/opengl/Extensions3DOpenGLES.cpp.o: In function `WebCore::Extensions3DOpenGLES::supportsExtension(WTF::String const&)':
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0xe8): undefined reference to `eglGetProcAddress'
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0xf8): undefined reference to `eglGetProcAddress'
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0x108): undefined reference to `eglGetProcAddress'
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0x118): undefined reference to `eglGetProcAddress'
Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0x134): undefined reference to `eglGetProcAddress'
../../lib/../Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/opengl/Extensions3DOpenGLES.cpp.o:Extensions3DOpenGLES.cpp:(.text._ZN7WebCore20Extensions3DOpenGLES17supportsExtensionERKN3WTF6StringE+0x144): more undefined references to `eglGetProcAddress' follow
collect2: error: ld returned 1 exit status
Source/WebKit/CMakeFiles/WebKit.dir/build.make:2588: recipe for target 'lib/libQt5WebKit.so.5.212.0' failed
make[4]: *** [lib/libQt5WebKit.so.5.212.0] Error 1
CMakeFiles/Makefile2:1102: recipe for target 'Source/WebKit/CMakeFiles/WebKit.dir/all' failed
`

It seems that the opengl lib is not included in the build?

**Comment by annulen** [comment]
Looks like the same issue as in https://github.com/voidlinux/void-packages/pull/6876

**Comment by schoeffi91** [comment]
It seems that  Qt5Gui_EGL_LIBRARIES and Qt5Gui_OPENGL_LIBRARIES in Source/WebCore/PlatformQt.cmake are empty. 
```
        list(APPEND WebCore_LIBRARIES
            ${Qt5Gui_EGL_LIBRARIES}
            ${Qt5Gui_OPENGL_LIBRARIES}
        )
```
When i replace the envs with my direct path to libEGL.so and ibGLESv2.so the build/link process finished. (Not testet on device!)

**Comment by Vogtinator** [comment]
I already debugged this here and found the issue:

https://github.com/annulen/webkit/issues/598

**Comment by annulen** [comment]
Should be fixed after 8fd4477 and 7ec8dd4

**Comment by crystalligentSoftware** [comment]
The compilation works now. But again i have to change the defines for the egl libraries.

```
      list(APPEND WebCore_LIBRARIES
           `${Qt5Gui_EGL_LIBRARIES}`
            ${Qt5Gui_OPENGL_LIBRARIES}
        )
```
Otherwise there are many linker errors. (With Qt 5.9.2 now)
I build the Webkit with buildroot for imx6.

**Comment by annulen** [comment]
If your ${Qt5Gui_EGL_LIBRARIES} and ${Qt5Gui_OPENGL_LIBRARIES} are empty, this means your installation of Qt is broken
