### ISSUE TITLE
Can't load local pages

### ISSUE THREAD

**Issue by niXman** [annulen/webkit#602]
Hi,

I try to load local hello world page:
```
QUrl url("/home/nixman/d/html/index.html");
webview->load(url);
```
but I can't see this page.

In the Inspect I can see `Failed to load resource: Cannot open file:///home/nixman/d: Path is a directory`
What am I doing wrong?

**Comment by annulen** [comment]
Use `QUrl url = QUrl::fromLocalFile("/home/nixman/d/html/index.html");` or full URL with `file://` scheme. Both should work fine

**Comment by niXman** [comment]
Thanks, works as expected.

Closed.
