### ISSUE TITLE
Webpages/resources in the .qrc file

### ISSUE THREAD

**Issue by niXman** [annulen/webkit#603]
Using qt-4.8 I can put webpages/scripts/resources into .qrc file and then register it using `QResource::registerResource` function and later I can load webpages/scripts/resources using the `qrc:/index.html` as path.

My question is: can I do this using your WebKit project?

**Comment by annulen** [comment]
Yes, why not? FYI, Inspector UI works in this way internally

**Comment by niXman** [comment]
Ok, thanks!
