### ISSUE TITLE
WebCore symbols are not hidden properly

### ISSUE THREAD

**Issue by mitya57** [annulen/webkit#611]
Hi!

[This code](https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/cmake/OptionsQt.cmake#L555) is supposed to hide the WebCore symbols. However, even though the `-fvisibility=hidden -fvisibility-inlines-hidden` flags are present in my build log, the WebCore symbols still end up in the list of exported symbols of `libQt5WebKit.so.5`.

Compared to Qt WebKit 5.9.1, 3231 new symbols are added that start with `_ZN7WebCore`. The 5.9.1 version had just 3119 symbols, so the number has grown more than twice.

Do you have any idea how to fix this?

**Comment by annulen** [comment]
A lot of WebCore symbols are now exported via WEBKIT_EXPORT macro. Making this macro no-op will probably help

**Comment by mitya57** [comment]
I guess you mean `WEBCORE_EXPORT`, which in turn uses `WTF_EXPORT_DECLARATION`. I will try to patch it.

**Comment by annulen** [comment]
Yes

**Comment by mitya57** [comment]
This patch greatly reduces the number of symbols for me:
```diff
--- a/Source/WTF/wtf/ExportMacros.h
+++ b/Source/WTF/wtf/ExportMacros.h
@@ -56,7 +56,7 @@
 
 #elif defined(__GNUC__) && !defined(__CC_ARM) && !defined(__ARMCC__)
 
-#define WTF_EXPORT_DECLARATION __attribute__((visibility("default")))
+#define WTF_EXPORT_DECLARATION
 #define WTF_IMPORT_DECLARATION WTF_EXPORT_DECLARATION
 #define WTF_HIDDEN_DECLARATION __attribute__((visibility("hidden")))
 
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -546,6 +546,7 @@
     if (NOT SHARED_CORE)
         set(CMAKE_C_FLAGS "-fvisibility=hidden ${CMAKE_C_FLAGS}")
         set(CMAKE_CXX_FLAGS "-fvisibility=hidden -fvisibility-inlines-hidden ${CMAKE_CXX_FLAGS}")
+        add_definitions(-DJS_NO_EXPORT)
     endif ()
 endif ()
```

Maybe you can apply at least the second part of it?

**Comment by annulen** [comment]
I'm hesistating to change WTF_EXPORT_DECLARATION, I think WEBCORE_EXPORT needs to be changed instead.

As for JS_NO_EXPORT, looks like it was not defined in old QtWebKit build system, so those symbols were public.

**Comment by mitya57** [comment]
No problem, we (Debian) will have it as a distro patch then. Thanks anyway!

**Comment by mitya57** [comment]
> I'm hesistating to change WTF_EXPORT_DECLARATION, I think WEBCORE_EXPORT needs to be changed instead.

I would change it, but it is defined in too many places:
```
Source/WebCore/WebCorePrefix.h:#define WEBCORE_EXPORT WTF_EXPORT_DECLARATION
Source/WebCore/platform/PlatformExportMacros.h:#define WEBCORE_EXPORT WTF_EXPORT
Source/WebCore/platform/PlatformExportMacros.h:#define WEBCORE_EXPORT
Source/WebCore/testing/js/WebCoreTestSupportPrefix.h:#define WEBCORE_EXPORT WTF_EXPORT_DECLARATION
Source/WebKit/qt/WebKitPrefix.h:#define WEBCORE_EXPORT WTF_EXPORT_DECLARATION
Source/WebKit/qt/WebKitWidgetsPrefix.h:#define WEBCORE_EXPORT WTF_IMPORT_DECLARATION
Source/WebKit2/config.h:#define WEBCORE_EXPORT WTF_EXPORT_DECLARATION
```

So to keep our patch smaller, we will redefine `WTF_EXPORT_DECLARATION` (unless it starts breaking other stuff, of course).
