### ISSUE TITLE
Incorrect layout

### ISSUE THREAD

**Issue by ajankov** [annulen/webkit#616]
I am testing with current alpha2 release and the attached HTML is rendered incorrectly. The word-wrap:break-word is not honored. It should break the long word in first cell but it doesn't and it overlaps the text in the next cells. Chrome and Edge work well. 

Do you plan a new release to include the latest changes in repository and eventually a newer version of upstream WebKit? Is there any time estimation for such a possible new release?

Is alpha2 the latest stable release I can test now?

Thanks.

[wordwrap.zip](https://github.com/annulen/webkit/files/1269631/wordwrap.zip)

**Comment by annulen** [comment]
Looks like a WebKit upstream bug that is fixed in current trunk

**Comment by ajankov** [comment]
Thanks for taking a look at this. Is there a newer qtwebkit release which fixes this that I can try now? 

Do you plan a new release to include the latest changes and eventually a newer WebKit?

**Comment by ajankov** [comment]
Do you have any newer release or stable snapshot with updated WebKit I can test? Are you planning any beta release soon? Thanks.

**Comment by annulen** [comment]
I've identified which commit fixes the bug, next release will contain backport

https://bugs.webkit.org/show_bug.cgi?id=171108

**Comment by ajankov** [comment]
Great! Do you have any rough estimation about when the next release could be? Thank you.

**Comment by annulen** [comment]
Fixed in 4daf652a9ee6ac29d77cc5ab50403c5f97451d34
