### ISSUE TITLE
Windows build using shared libxml2/libxslt

### ISSUE THREAD

**Issue by dougmassay** [annulen/webkit#622]
Is there a trick to building on Windows against dll versions of libxml2/libxslt (like the binary release of 5.212.0-alpha2) instead of the static ones? The build-script only seems to download/use the static versions in qtwebkit-libs-win. I have no issue building my own libxml2/libxslt dlls, I'm just uncertain how to tell the build-script to link to the shared versions instead.

Ideally, I'm hoping there's some sort of road map for building the exact same Windows binary release that's available for download in the 5.212.0-Alpha2 release.

**Comment by annulen** [comment]
CI system which build binaries that you download uses Conan to obtain some dependencies. Conanfile is at http://code.qt.io/cgit/qt/qt5.git/tree/coin/provisioning/qtci-windows-10-x86_64/conanfiles/qtwebkit.txt

Script that invokes conan is at http://code.qt.io/cgit/qt/qt5.git/tree/coin/provisioning/common/03-conan.ps1#n46 (no real magic, it just sets target arch and compiler explicitly and verifies manifests, if you run it manually just using defaults may be fine). To use conan you need to pass -DQT_CONAN_DIR=... to cmake and set it to path where conanbuildinfo.cmake is located.

Other dependencies, notably libjpeg, libpng, zlib, sqlite, are re-used from Qt build.

Yes, I know this all needs to be documented :)

**Comment by dougmassay** [comment]
Thanks for the pointers. I need to try and incorporate the latest libxml2 (v2.9.5) as they finally got around to fixing a pesky reversion bug (in v2.9.3 & .4) that can cause problems with projects that use WebKit. It causes html entities to be expanded twice under certain conditions (on all platforms).

The bug:
https://bugzilla.gnome.org/show_bug.cgi?id=760367

And the commit to fix it:
https://git.gnome.org/browse/libxml2/commit/?id=3f0627a1ee854dc965bf61dd6466a798b80cf088

No need to explain about documentation. I know first hand how hard it is to force oneself to set aside time to fully document procedures (or to find someone willing to do it for you). I don't mind a little digging. Your tips should help a lot! Thanks again.

**Comment by annulen** [comment]
Sounds like we need to update packages in CI as well

**Comment by dougmassay** [comment]
You'd certainly be doing me a favor if you did. :)

**Comment by annulen** [comment]
Replaced with #655
