### ISSUE TITLE
selectedRange sometimes return 0 and can cause segfaults

### ISSUE THREAD

**Issue by rapgro** [annulen/webkit#627]
https://github.com/annulen/webkit/blob/649325efa421aefb78e1655f2e228384d7b673dc/Source/WebKit/qt/WebCoreSupport/QWebPageAdapter.cpp#L393

selectedRange sometimes returns 0 but this file pointer is assumed to be always not NULL. The caller may not know about selection state (if something is selected at all). Please add a check to QWebPageAdapter::selectedHtml and return an empty string in case.

An example is given in Editor::replaceSelectionWithText : 
https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/WebCore/editing/Editor.cpp#L552

Pitfalls
PassRefPtr
Programmers who worked on WebKit before C++11 are familiar with a class template called PassRefPtr (soon to be renamed to DeprecatedPassRefPtr) and you will see it in older WebKit code.
https://webkit.org/blog/5381/refptr-basics/

**Comment by annulen** [comment]
PassRefPtr cannot cause segfaults

Duplicate pf #573

**Comment by rapgro** [comment]
Some more debugging in the hope to make it more clear through just static code review:
https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/WebCore/editing/Editor.cpp#L561
https://github.com/annulen/webkit/blob/qtwebkit-stable/Source/WebCore/editing/VisibleSelection.cpp#L135

**Comment by rapgro** [comment]
Please watch this video: http://www.yousubtitles.com/Preventing-null-pointer-exceptions-at-compile-time-by-Michael-Ernst-and-Werner-Dietl-id-775571

**Comment by annulen** [comment]
Fixed
