### ISSUE TITLE
ScudCloud noworky

### ISSUE THREAD

**Issue by UnitedMarsupials** [annulen/webkit#631]
Hello!
As is being discussed in raelgc/scudcloud#594, the change of the qt5-webkit version from the old (5.7.1) to 5.212.* is a suspect in why ScudCloud -- an open-source alternative for Slack instant-messenger client -- is broken for some people, including this reporter.

Would anyone from this project care to investigate? Thanks!

**Comment by annulen** [comment]
FWIW, slack.com works fine here in plain QtWebKit

**Comment by annulen** [comment]
Could you try to open slack.com in any QtWebKit-based browser, e.g. Otter?

**Comment by UnitedMarsupials** [comment]
> Could you try to open slack.com in any QtWebKit-based browser, e.g. Otter?

Yes, I was able to open https://slack.com/ in otter-browser. That worked even though it also said, on stderr:
`qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set1_groups`
 But that's not the same as using Slack. Unfortunately, https://MYCOMPANY.slack.com/ does not work, because Slack refuses to work in Otter -- "unsupported browser". I do not know, how to spoof `User-Agent` header with Otter...

**Comment by annulen** [comment]
Oh, indeed - Otter uses made-up UA string instead of default one, so some sites that should normally work with default UA of QtWebKit may be broken or work differently (cc @Emdek). 

Use "View / User Agent" menu

**Comment by annulen** [comment]
>cannot resolve SSL_CTX_set1_groups

Which OpenSSL version are you using?

**Comment by UnitedMarsupials** [comment]
I can confirm now -- after forcibly downgrading qt5-webkit on my system back to 5.7.1, scudcloud starts up fine. I went back and forth between the two versions several times -- 5.7.1 works, 5.212.alpha2 does not :(

**Comment by UnitedMarsupials** [comment]
I just tested with another Slack-client -- [diligent](/trueos/diligent/). The same problem -- works with 5.7.1, but not with 5.212.a2.

**Comment by annulen** [comment]
Thanks, it will be less cumbersome to debug it for me

**Comment by annulen** [comment]
I've checked diligent, it works fine here

**Comment by UnitedMarsupials** [comment]
Was hanging for me here, until I downgraded qt-webkit :( The initial login part works (for both it and scudcloud), but then it just hangs...

**Comment by annulen** [comment]
So, problem doesn't reproduce with diligent here, I can try to check scudcloud

**Comment by annulen** [comment]
Could you try Qt 5.9 with diligent? It works fine here

**Comment by UnitedMarsupials** [comment]
> Could you try Qt 5.9 with diligent?

Not easily... FreeBSD's ports still only install Qt-5.7.1

**Comment by annulen** [comment]
Fixed in 5648446
