### ISSUE TITLE
libpng warning: iCCP issue

### ISSUE THREAD

**Issue by Cobra91151** [annulen/webkit#639]
Hi! I get those warnings with QtWebKit 5.212.0 Alpha 2 (Qt 5.9.2) when use QWebView:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

I think some of your project images contain incorrect sRGB profile. To fix it please open/save as and replace them using ImageMagick Display program. Thank you.

**Comment by annulen** [comment]
This is already fixed in f53b6b8cfef091770dd3dccd8371420b63d89f83 and will be included into next release

**Comment by Cobra91151** [comment]
Any news about the next release date? Thanks.

**Comment by annulen** [comment]
Next week

**Comment by Cobra91151** [comment]
Ok. Thank you.

**Comment by Cobra91151** [comment]
So when will be release? Thanks.
