### ISSUE TITLE
Check loadFinished behavior with error pages

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#640]
If I understand correctly, if error page extension is used, `loadFinished(false)` is not emitted for failed load (`FrameLoaderClientQt::dispatchDidFailProvisionalLoad`), and instead it is emitted with loading result of error page itself (most likely `true`).

When we added error pages by default, it changes behavior in code that expects to process `false`. Probably we should still emit `loadFinished(false)` when built-in error page is loaded.

**Comment by Emdek** [comment]
Documentation of `QWebFrame::loadFinished` says:

> This signal is emitted when a load of this frame is finished. ok will indicate whether the load was successful or any error occurred.

Any usage of error pages should never change that outcome in the first place.

**Comment by annulen** [comment]
Then it boils down to implementation of error page "marker", that can also be exposed as public QWebPage::isErrorPage
If loading finished and we display error page, emit `lodingFinished(false)`

**Comment by Emdek** [comment]
To be clear, marker should be per frame, and probably only there.

**Comment by Emdek** [comment]
Splitting out API part to #844.
