### ISSUE TITLE
HTMLMediaElement::TrackGroup Build Errors

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#646]
Error:
qtwebkit\source\webcore\html\HTMLMediaElement.cpp(294): error C2039: 'TrackGroup': is not a member of 'WebCore::HTMLMediaElement'

This seems to happen if the following is defined in the cmake command:
-DENABLE_VIDEO=ON -DENABLE_VIDEO_TRACK=OFF

Looking at the header code the TrackGroup is inside the `#if ENABLE(VIDEO_TRACK)` block, but in the cpp it is not. Also it looks like there are other functions hidden inside this block in the header that are not hidden in the cpp file.

Should these 2 items always be ON at the same time? if so the cmake files should define a dependency between these 2 options.

**Comment by annulen** [comment]
I think building this combination is not supported

**Comment by annulen** [comment]
It should be safe to change public options, i.e. those displayed in ccmake before you press `t` or in cmake-gui without enabling "Advanced" checkbox. Everything else is at your own risk.

**Comment by izzyonstage** [comment]
I agree.
But the cpp file surely should wrap that struct in the same `#if...` ?

I have never used ccmake or the gui. I build purely via trial and error using `cmake -DPORT="Qt"...`
If this is configuration is not supported then in the qt platform file it should turn both OFF if either one is OFF?
That is just my opinion though

I am currently trying to get some basic video support in my windows build (hence the trial and error of turning options on/off)

**Comment by annulen** [comment]
```diff
diff --git a/Source/cmake/OptionsQt.cmake b/Source/cmake/OptionsQt.cmake
index f36178d4a66..b00a31a3df0 100644
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -283,6 +283,10 @@ WEBKIT_OPTION_DEPEND(ENABLE_3D_TRANSFORMS ENABLE_OPENGL)
 WEBKIT_OPTION_DEPEND(ENABLE_ACCELERATED_2D_CANVAS ENABLE_OPENGL)
 WEBKIT_OPTION_DEPEND(ENABLE_WEBGL ENABLE_OPENGL)
 
+# Building video without these options is not supported
+WEBKIT_OPTION_DEPEND(ENABLE_VIDEO ENABLE_VIDEO_TRACK)
+WEBKIT_OPTION_DEPEND(ENABLE_VIDEO ENABLE_MEDIA_CONTROLS_SCRIPT)
+
 # WebAudio and MediaSource are supported with GStreamer only
 WEBKIT_OPTION_DEPEND(ENABLE_WEB_AUDIO USE_GSTREAMER)
 WEBKIT_OPTION_DEPEND(ENABLE_LEGACY_WEB_AUDIO USE_GSTREAMER)
```

**Comment by izzyonstage** [comment]
Great stuff.
I will apply that to my build and set the relevant options

Thanks
