### ISSUE TITLE
parsePortFromStringPosition ODR violation

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#647]
Not sure if this is just me not setting the correct enable values for cmake configuration but...

I currently get the following when I set the `-DENABLE_MEDIA_STREAM=ON` option on windows:
```
.\qtwebkit\source\webcore\html\URLUtils.h(139): error C2084: function 'unsigned int WebCore::parsePortFromStringPosition(const WTF::String &,unsigned int,unsigned int &)' already has a body
.\qtwebkit\source\webcore\html\HTMLAnchorElement.cpp(80): note: see previous definition of 'parsePortFromStringPosition'
```
It appears both those files define the same function.
Should this be split out into a different header to be included by both scripts to avoid duplicate body definitions?

I am just running a build where I have made this change locally to see what happens.

**Comment by izzyonstage** [comment]
Apparently now it fails with the following errors:

```
.\qtwebkit\Source\WTF\wtf/NeverDestroyed.h(53): error C2248: 'WebCore::MediaStreamRegistry::MediaStreamRegistry': cannot access private member declared in class 'WebCore::MediaStreamRegistry'
.\qtwebkit\Source\WebCore\Modules\mediastream\MediaStreamRegistry.cpp(65): note: see declaration of 'WebCore::MediaStreamRegistry::MediaStreamRegistry'
.\qtwebkit\source\webcore\modules\mediastream\MediaStreamRegistry.h(42): note: see declaration of 'WebCore::MediaStreamRegistry'
.\qtwebkit\Source\WebCore\Modules\mediastream\MediaStreamRegistry.cpp(42): note: see reference to function template instantiation 'WTF::NeverDestroyed<WebCore::MediaStreamRegistry>::NeverDestroyed<>(void)' being compiled
.\qtwebkit\Source\WebCore\Modules\mediastream\MediaStreamRegistry.cpp(42): note: see reference to function template instantiation 'WTF::NeverDestroyed<WebCore::MediaStreamRegistry>::NeverDestroyed<>(void)' being compiled
```
Any ideas on this? or is this another unsupported option maybe?

**Comment by annulen** [comment]
Kind of.

There are 2 backends for MediaStream: AVFoundation (macOS) and OpenWebRTC (depends on GStreamer and other stuff). Seems like there were no attempts to build MediaStream code with MSVC, as neither of these backends is interesting for Windows people.

I also doubt that you need this feature. Are building QtWebKit for PhantomJS? Do you need to capture user audio/video, e.g. from webcam? If answer is yes, it can be solved without pulling in openwebrtc, though if you need full WebRTC support there is no way around yet.

**Comment by izzyonstage** [comment]
I thought as much.

Yes this is to be used with PJS and I was hoping to be able to capture video (so I can apply custom watermark before uploading to service provider APIs).
Not a major thing for now.
Was really just playing about with more options to see what would happen with msvc build.

**Comment by izzyonstage** [comment]
I am guessing that `ENABLE_MEDIA_CAPTURE` is also a similar thing to this?

**Comment by annulen** [comment]
ENABLE_MEDIA_CAPTURE guards implementation of `capture` HTML attribute (https://www.w3.org/TR/html-media-capture/). It has no direct connection to MediaStream or WebRTC, intead it allows to attach media capture to the form.

If I understand correctly, it can be easily forwarded to public API in a way similar to `QWebPage::ChooseMultipleFilesExtension`, and you will be able to capture media in your code e.g. via Qt Multimedia (or any other means), save it to file, and pass this file path back to WebKit. IOW, it's just like usual file upload but with a property that capturing user media is allowed.

**Comment by annulen** [comment]
Closing this for now, for MEDIA_CAPTURE opened #650
