### ISSUE TITLE
Fix build with x32 ABI

### ISSUE THREAD

**Issue by mitya57** [annulen/webkit#668]
Please cherry-pick 0858ee607f376ae86c20c3cb4bcdb2c41b3e2b9f from master. Applies cleanly (modulo the changelog part).

Should fix https://bugs.debian.org/881055.

**Comment by annulen** [comment]
Whoa, discussed this issue on the previous week on #webkit channel with Debian user, didn't know it was already fixed in trunk

**Comment by annulen** [comment]
Fixed in 29e501cdab402183f9999fe3c95b510485feb606
