### ISSUE TITLE
[question] specifying installation locations

### ISSUE THREAD

**Issue by RJVB** [annulen/webkit#674]
Hi,

I can't seem to determine exactly how to specify where items are installed. Setting `-DLIB_INSTALL_DIR=$prefix/libexec/qt5/Library/Frameworks` has the partial effect of putting the QtWebKit and QtWebKitWidgets framework bundles in that location, but
- the bundles lack the Contents/QtWebKit[Widgets] symlink to the actual framework binary
- the library ID is still set to a file under `$prefix/lib`.

The former is just a nuisance that I can correct easily enough, the latter is a real PITA - and I cannot seem to find why this goes wrong and how to correct it. FWIW, the stock Qt QtWebKit build using QMake installs everything exactly where it should go.

Curiously I see that `KDE_INSTALL_USE_QT_SYS_PATHS` gets set, but what I'm getting are not my Qt system paths but what I'd call "the standard system paths in the prefix where Qt is installed".

This is on Mac but I reckon that the same mechanism should apply elsewhere.

**Comment by RJVB** [comment]
Sorry, my bad. I always forget about CMake's kind of unintuitive (to me) CMAKE_INSTALL_NAME_DIR property. It was actually set wrong; correcting that fixed this issue.

**Comment by annulen** [comment]
>The former is just a nuisance that I can correct easily enough, the latter is a real PITA - and I cannot seem to find why this goes wrong and how to correct it. FWIW, the stock Qt QtWebKit build using QMake installs everything exactly where it should go.

Don't worry, I think you are the first person to try out such customizations - Homebrew didn't make package yet, and for me it was enough that CI artifacts have correct layout

However, I'm not sure bug is in the project files. We are using built-in cmake capability of making framework bundle and installing it. Both frameworks are installed to LIB_INSTALL_DIR - see Source/WebKit/CMakeLists.txt and Source/WebKit/PlatformQt.cmake.

>the bundles lack the Contents/QtWebKit[Widgets] symlink to the actual framework binary

What? I don't see any Contents in frameworks create by Qt
```
ls -o /mnt/storage/5.9/clang_64/lib/QtCore.framework/
total 8
lrwxrwxrwx 1 ktokarev   24 Apr  7  2017 Headers -> Versions/Current/Headers
lrwxrwxrwx 1 ktokarev   23 Apr  7  2017 QtCore -> Versions/Current/QtCore
lrwxrwxrwx 1 ktokarev   29 Apr  7  2017 QtCore_debug -> Versions/Current/QtCore_debug
-rw-r--r-- 1 ktokarev 1330 Apr  4  2017 QtCore_debug.prl
-rw-r--r-- 1 ktokarev 1326 Apr  4  2017 QtCore.prl
lrwxrwxrwx 1 ktokarev   26 Apr  7  2017 Resources -> Versions/Current/Resources
drwxr-xr-x 3 ktokarev   28 Apr  7  2017 Versions
```
>the library ID is still set to a file under  $prefix/lib .

What is it?

**Comment by RJVB** [comment]
On Sunday November 12 2017 14:52:41 Konstantin Tokarev wrote:

> What? I don't see any Contents in frameworks create by Qt

Sorry, slip of the fingers, framework bundles don't have a Contents directory.


> >the library ID is still set to a file under  $prefix/lib .
> 
> What is it?

On OS X, each library has an ID which is usually either the filename or the full path. If the full path, this is the access path that will be stored as a "library-specific rpath" in an executable or other library linking to that library, and in that case the dynamic linker will insist on accessing the dependency via that path.
That's the PITA: you can change a library's ID (using install_name_tool), but you'll also have to find all its dependents and update them.

R.
