### ISSUE TITLE
webcore problem with qtsqlite

### ISSUE THREAD

**Issue by developernew123** [annulen/webkit#680]
I get this when I configure build-webkit script although I built qt 5.6 with sqlite support 

CMake Error: install(EXPORT "WebKitTargets" ...) includes target "WebCore" which requires target "qtsqlite" that is not in the export set

this is my configuration 

perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=E:\programs\qt6 -DENABLE_WEBKIT2=OFF -DUSE_STATIC_RUNTIME=ON"

**Comment by annulen** [comment]
That's weird, `qtsqlite` target is STATIC and needs not to be installed

**Comment by annulen** [comment]
Ah, you build with static Qt

**Comment by developernew123** [comment]
I don't understand , why doesn't webcore find qtsqlite although I have Qt5Sql.lib in qt libs dir and qsqlite.lib in qt plugins dir and sqlite3.lib in WebKitLibraries\win\lib32

this is my configuration of qt 5.6

configure -static -static-runtime -release -prefix E:\programs\qt6 -icu -I E:\programs\icu\include -L E:\programs\icu\lib -openssl -I C:\openssl\include -L C:\openssl\lib -openssl-linked -l Gdi32 -l crypt32 -l User32 OPENSSL_LIBS="-lssleay32 -llibeay32" -platform win32-msvc2015 -qt-zlib -qt-pcre -qt-libpng -qt-libjpeg -qt-freetype -qt-sql-sqlite -qt-sql-odbc -nomake tests -plugin-sql-sqlite -opensource

**Comment by developernew123** [comment]
what should I do to make webcore find qtsqlite

**Comment by annulen** [comment]
* Qt5Sql.lib is unrelated, it provides QtSql API, not sqlite
* qsqlite.lib is Qt plugin, it also isn't sqlite library
* sqlite3.lib in WebKitLibraries\win\lib32 is indeed  what is needed, but presumably you've set SQLITE3SRCDIR variable and it was not used

**Comment by developernew123** [comment]
I've already set this variable which points to sqlite headers and source files before , this means I should remove it ?

**Comment by developernew123** [comment]
It now works after I deleted this var

**Comment by annulen** [comment]
This patch should fix case when SQLITE3SRCDIR is used

```diff
diff --git a/Source/cmake/OptionsQt.cmake b/Source/cmake/OptionsQt.cmake
index 4a7303c3691..e487dd53093 100644
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -394,6 +394,7 @@ if (SQLITE3_SOURCE_DIR)
     add_library(qtsqlite STATIC ${SQLITE_SOURCE_FILE})
     target_compile_definitions(qtsqlite PUBLIC -DSQLITE_CORE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE)
     WEBKIT_SET_EXTRA_COMPILER_FLAGS(qtsqlite)
+    QT_ADD_EXTRA_WEBKIT_TARGET_EXPORT(qtsqlite)
     set(SQLITE_LIBRARIES qtsqlite)
     set(SQLITE_FOUND 1)
 else ()
```
