### ISSUE TITLE
Missing Angle Link Info

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#681]
Although QtWebKit builds I have a problem when linking to it from PhantomJS:

```
WebCore.lib(GraphicsContext3DQt.cpp.obj) : error LNK2001: unresolved external symbol "void __cdecl ShInitBuiltInResources(struct ShBuiltInResources *)" (?ShInitBuiltInResources@@YAXPAUShBuiltInResources@@@Z)
--
WebCore.lib(GraphicsContext3DOpenGLCommon.cpp.obj) : error LNK2001: unresolved external symbol "bool __cdecl ShCheckVariablesWithinPackingLimits(int,struct ShVariableInfo *,unsigned int)" (?ShCheckVariablesWithinPackingLimits@@YA_NHPAUShVariableInfo@@I@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "bool __cdecl ShInitialize(void)" (?ShInitialize@@YA_NXZ)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "void * __cdecl ShConstructCompiler(unsigned int,enum ShShaderSpec,enum ShShaderOutput,struct ShBuiltInResources const *)" (?ShConstructCompiler@@YAPAXIW4ShShaderSpec@@W4ShShaderOutput@@PBUShBuiltInResources@@@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "void __cdecl ShDestruct(void *)" (?ShDestruct@@YAXPAX@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "bool __cdecl ShCompile(void * const,char const * const * const,unsigned int,int)" (?ShCompile@@YA_NQAXQBQBDIH@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl ShGetInfoLog(void * const)" (?ShGetInfoLog@@YAABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAX@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl ShGetObjectCode(void * const)" (?ShGetObjectCode@@YAABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAX@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "class std::vector<struct sh::Uniform,class std::allocator<struct sh::Uniform> > const * __cdecl ShGetUniforms(void * const)" (?ShGetUniforms@@YAPBV?$vector@UUniform@sh@@V?$allocator@UUniform@sh@@@std@@@std@@QAX@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "class std::vector<struct sh::Varying,class std::allocator<struct sh::Varying> > const * __cdecl ShGetVaryings(void * const)" (?ShGetVaryings@@YAPBV?$vector@UVarying@sh@@V?$allocator@UVarying@sh@@@std@@@std@@QAX@Z)
WebCore.lib(ANGLEWebKitBridge.cpp.obj) : error LNK2001: unresolved external symbol "class std::vector<struct sh::Attribute,class std::allocator<struct sh::Attribute> > const * __cdecl ShGetAttributes(void * const)" (?ShGetAttributes@@YAPBV?$vector@UAttribute@sh@@V?$allocator@UAttribute@sh@@@std@@@std@@QAX@Z)
..\bin\phantomjs.exe : fatal error LNK1120: 11 unresolved externals
```
What am I missing, or is this not supported?

I am building Qt with -opengl desktop and it should be building angle for use with it too.
Wondering if this should be set to dynamic?

**Comment by annulen** [comment]
In thory this should work, but there is no configuration with `-opengl desktop` on Windows in CI so it's left completely untested.

QtWebKit builds only a part of ANGLE to use its shader compiler, it's totally unrelated to ANGLE used or not used in QtGui.

**Comment by annulen** [comment]
Could you check how Source/ThirdParty/ANGLE/include/GLSLANG/ShaderLang.h is defined? Looks like trouble is because of static build, not `-opengl dynamic` - probably static builds were so far tested on Windows with -DENABLE_OPENGL=OFF only

**Comment by annulen** [comment]
nvm, I think I've found the issue - libANGLESupport.a needs to be linked to final executable and it probably isn't

**Comment by izzyonstage** [comment]
I have an ANGLESupport.lib created in lib folder of Qt installation

**Comment by annulen** [comment]
Is it linked to phantomjs binary?

**Comment by izzyonstage** [comment]
Not that I can tell. Should that not be defined in one of the *.pri files?

**Comment by izzyonstage** [comment]
Also wondering should the version of ANGLE not use the same source from QtBase?
Is there any way to tell the build to include a different ANGLE include directory instead?

**Comment by annulen** [comment]
It should be but it isn't. Which again leads me to the idea that current code with ifs needs to be replaced with more generic approach, i.e. we should iterate all dependencies of cmake's WebKit target

**Comment by annulen** [comment]
qtsqlite will also need to be handled (https://github.com/annulen/webkit/issues/680)

**Comment by izzyonstage** [comment]
Strange, I don't have a problem with sqlite at all

**Comment by annulen** [comment]
>Also wondering should the version of ANGLE not use the same source from QtBase?

Using different version of ANGLE means that you may need to adjust WebKit code to API changes if there are any. So, only bundled version of ANGLE is supported.

>Is there any way to tell the build to include a different ANGLE include directory instead?

No, by design. However there were 3rd party patches for old build system, IIRC some distribution was used same ANGLE version in both places.

Also note that if you build Qt with desktop opengl, Qt is not building ANGLE at all.

It should be possible to make this supported in future, if someone volunteers to update ANGLE in both Qt and WebKit trunk so they use same version most of the time.

>Strange, I don't have a problem with sqlite at all

I guess you are using external sqlite dependency, not SQLITE3_SOURCE_DIR environment variable

**Comment by annulen** [comment]
And also note that QtWebKit builds just shader compiler, not the whole ANGLE

**Comment by izzyonstage** [comment]
> Also note that if you build Qt with desktop opengl, Qt is not building ANGLE at all.

I am building with the desktop flag, but unless I use the -no-angle it still seems to build ANGLE in.
Might try swapping to dynamic as that is suggested in all Qt documentation I have seen v5.6+

> I guess you are using external sqlite dependency, not SQLITE3_SOURCE_DIR environment variable

Correct, I am building the latest sqlite source dynamically as part of my build system. Then when I build Qt & QtWebKit I add the relevant ouptu directories to the global include and lib environment variables for MSVC.

Just out of curiosity how old is the ANGLE version in the repo? I might try my hand at updating it over the weekend to see what happens in my CI system.

**Comment by annulen** [comment]
>Might try swapping to dynamic as that is suggested in all Qt documentation I have seen v5.6+

If you are making redistributable binaries, prefer dynamic. If it's for local consumption, use what fits better (dynamic adds extra indirection which may be uneeded)

>Correct, I am building the latest sqlite source dynamically as part of my build system.

That's why you are unaffected (but others are not so lucky)

>Just out of curiosity how old is the ANGLE version in the repo?

AFAIU it's at google/angle@b11e2483742db884bd0af41f78f528240577356b.

AFAIU trunk uses google/angle@d1bed175f107143a7c52485a9d197b486cd5433e now, and there were changes in WebKit code for each upgrade

>Is that all that is required to support the WebGL implementation 

It's also used by AcceleratedCompositing (which is irrelevant in case of PhantomJS)

**Comment by developernew123** [comment]
does this mean that I should build sqlite dynamically

**Comment by annulen** [comment]
No

**Comment by developernew123** [comment]
So what should I do

**Comment by developernew123** [comment]
I don't understand , why doesn't webcore find qtsqlite although I have Qt5Sql.lib in qt libs dir and qsqlite.lib in qt plugins dir and sqlite3.lib in WebKitLibraries\win\lib32

**Comment by annulen** [comment]
Replaced with #695
