### ISSUE TITLE
which qt configuration is valid

### ISSUE THREAD

**Issue by developernew123** [annulen/webkit#687]
is this qt coniguration valid and will be ok when I build webkit 

configure -static -static-runtime -release -prefix E:\programs\qt6 -openssl -I C:\openssl\include -L C:\openssl\lib -openssl-linked -l Gdi32 -l crypt32 -l User32 OPENSSL_LIBS="-lssleay32 -llibeay32" -platform win32-msvc2015 -qt-pcre -qt-freetype -nomake tests -opensource -system-zlib -system-libpng -system-libjpeg -plugin-sql-sql -qt-sql

**Comment by annulen** [comment]
You don't really need `-plugin-sql-sql -qt-sql`, otherwise looks fine

**Comment by developernew123** [comment]
I don't need them for webkit but I need them for some purposes

**Comment by annulen** [comment]
You also didn't specify if you are running this for qt-everywhere tarball (or qt5.git), or for qtbase only. If the latter, you'll need to disable geolocation and device orientation support in QtWebKit (though the latter is not really useful on desktop anyway, besides increasing html5test score :)

**Comment by developernew123** [comment]
for qt-everywhere source which has qtbase surely
Is there a difference between them ?

**Comment by annulen** [comment]
You can build only qtbase or qtbase with other modules, in both cases your command line will work but result will be different

**Comment by developernew123** [comment]
I finished building and all tests were built but when I run anyone of them in cmd I get

This application failed to start because it could not find or load the Qt platform plugin "windows"
in ""

**Comment by annulen** [comment]
Make sure that "qwindows" library is linked with that tests. However I doubt that anyone runs tests with static builds

**Comment by developernew123** [comment]
still not working I'll try to use these libraries in qt creator

**Comment by developernew123** [comment]
I can't build in qt creator I get 
mainwindow.obj:-1: error: LNK2001: unresolved external symbol "public: __thiscall QWebView::QWebView(class QWidget *)" (??0QWebView@@QAE@PAVQWidget@@@Z)

I copied webkit libraries to qt libs and included the headers .  this is my pro file



#-------------------------------------------------
#
# Project created by QtCreator 2017-12-01T23:04:38
#
#-------------------------------------------------

QT       += core gu webkit webkitwidgets 

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = untitled3
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += \
        main.cpp \
        mainwindow.cpp

HEADERS += \
        mainwindow.h

FORMS += \
        mainwindow.ui

win32:CONFIG(release, debug|release): LIBS += -LE:/programs/qt6/lib/ -lQt5WebKitWidgets
else:win32:CONFIG(debug, debug|release): LIBS += -LE:/programs/qt6/lib/ -lQt5WebKitWidgetsd
else:unix: LIBS += -LE:/programs/qt6/lib/ -lQt5WebKitWidgets

INCLUDEPATH += E:/programs/qt6/include
DEPENDPATH += E:/programs/qt6/include

win32-g++:CONFIG(release, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKitWidgets.a
else:win32-g++:CONFIG(debug, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKitWidgetsd.a
else:win32:!win32-g++:CONFIG(release, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/Qt5WebKitWidgets.lib
else:win32:!win32-g++:CONFIG(debug, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/Qt5WebKitWidgetsd.lib
else:unix: PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKitWidgets.a

win32: LIBS += -LE:/programs/qt6/lib/ -lQt5WebKitWidgets

INCLUDEPATH += E:/programs/qt6/include
DEPENDPATH += E:/programs/qt6/include

win32:!win32-g++: PRE_TARGETDEPS += E:/programs/qt6/lib/Qt5WebKitWidgets.lib
else:win32-g++: PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKitWidgets.a

win32:CONFIG(release, debug|release): LIBS += -LE:/programs/qt6/lib/ -lQt5WebKit
else:win32:CONFIG(debug, debug|release): LIBS += -LE:/programs/qt6/lib/ -lQt5WebKitd

INCLUDEPATH += E:/programs/qt6/include
DEPENDPATH += E:/programs/qt6/include

win32-g++:CONFIG(release, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKit.a
else:win32-g++:CONFIG(debug, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/libQt5WebKitd.a
else:win32:!win32-g++:CONFIG(release, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/Qt5WebKit.lib
else:win32:!win32-g++:CONFIG(debug, debug|release): PRE_TARGETDEPS += E:/programs/qt6/lib/Qt5WebKitd.lib

**Comment by developernew123** [comment]
which lib should I link against when building apps
