### ISSUE TITLE
The generated pkg-config file does not have a description

### ISSUE THREAD

**Issue by mitya57** [annulen/webkit#690]
Forwarding this from [Debian #884035](https://bugs.debian.org/884035):

> qt5webkit's pkgconfig file does not provide a description and this breaks the command `pkg-config --list-all --print-errors` (it stops in the middle when processing the qt5webkit file and exits). This in turn breaks jhbuild, which uses the above pkg-config command to determine if all necessary system dependencies are installed.

I looked at KDE and they fixed this recently in KDE/extra-cmake-modules@fd60f2b893d0b07f96f0fd715109cbd8d4e66140. It probably makes sense to upgrade to the latest version of that module and provide descriptions for Qt5WebKit and Qt5WebKitWidgets.

**Comment by thdouk** [comment]
Description is not the only thing missing. 
prefix, exec_prefix, libdir, includedir, Cflaqs and Requires are incomplete.
I was able to make it work by manually editing the Qt5WebKit.pc and Qt5WebKitWidgets.pc

**Comment by annulen** [comment]
fwiw #388 fixes some of this things

**Comment by annulen** [comment]
Fixed in 0325d51c4a2a05fb11b93f0c99d1d08976aac47d
