### ISSUE TITLE
use javascriptcore in external projects

### ISSUE THREAD

**Issue by developernew123** [annulen/webkit#691]
can I use javascriptcore in other projects which don't depend on qt

**Comment by annulen** [comment]
You can use JSCOnly port (build it from trunk, there are no releases), or use libjavascriptcoregtk provided by GTK port (depends on glib and ICU only)

**Comment by annulen** [comment]
On macOS you can use JSC framework shipped with the system. All three ports provide same C APIm which AFAIK doesn't have online documentation, but it sane ehough and you can get help on #webkit channel in freenode and on webkit-help mailing list. macOS framework also provides obj-c API, and GTK port provides GObject API
