### ISSUE TITLE
Github PRs Behaving Strangely

### ISSUE THREAD

**Issue by slackhead** [annulen/webkit#704]
Using 5.212.0_alpha2 on 64bit slackware 14.2
Qt 5.7.1

When I just made a PR on github the resulting page keeps telling me that "The content you are editing has changed. Please try again."

If I click update comment it still says the same message, but the PR went through alright.

**Comment by annulen** [comment]
If this is GitHub issue, please report it to the GitHub, as I cannot do anything with it
If you cannot create PR, you can report issue and embed path file into it, or share link to the patch or your branch with fix

**Comment by slackhead** [comment]
Sorry, I did explain very well. This only happens with qutebrowser using the webkit backend. It's fine with anything else.

**Comment by annulen** [comment]
I've just created PR and don't see any issues. What QtWebKit version are you using?

**Comment by slackhead** [comment]
5.212.0-alpha2

**Comment by annulen** [comment]
Could you show screenshot what happens?
Are there any JS errors in inspector's console?

**Comment by slackhead** [comment]
Well, I just tried creating a new PR and it was fine. I didn't see anything significant in the console.

I don't what happened but it seems ok now. I'll close this.
