### ISSUE TITLE
Where can I get the QCH formats Documentation

### ISSUE THREAD

**Issue by itviewer** [annulen/webkit#720]
I don't want complie this project myself，there is the online documentation for Qt5.5 http://doc.qt.io/archives/qt-5.5/qtwebkit-index.html.
but I don't know if it is outdated and suitable for QtWebKit 5.212.0

**Comment by annulen** [comment]
* All APIs documented in http://doc.qt.io/archives/qt-5.5/qtwebkit-index.html still work in the same way, as they are documented, with exception of things list as non-working in https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6 (in fact, from documented widgets API only TiledBackingStore does not work)
* There were a few clarifications in API, submitted after 5.5 release. Unfortunately, they are not published in HTML form.
* 5.212 contains a number of new APIs, some of them are documented in sources, some yet miss docs. Again, this is not published in HTML form yet

The only way to get HTML docs at the moment is to build them locally, or use documentation package from your distro if it is provided. This issue will be solved in the near time

**Comment by itviewer** [comment]
Thanks

**Comment by annulen** [comment]
#315, #721
