### ISSUE TITLE
WinDeployQt and QtWebKit DLLs

### ISSUE THREAD

**Issue by taalas** [annulen/webkit#729]
Hi,

I know that this is only partially on topic but:

I was very happy to see that this project is alive and have succesfully integrated the latest QtWebKit into an old project. We deploy our applications using WinDeployQt (or the OS's appropriate version) which detects the dependency for QtWebKit and *Widgets and tries to copy the DLL from the QtDir. It fails if the DLLs do not exist in that directory. To keep my QtDir clear I would like to copy the DLLs from somewhere else and skip them during automatic deployment. The --no-webkit flag does not seem to work. Has anybody had similar problems?

Thanks

**Comment by annulen** [comment]
To make your life easier you should install QtWebKit into Qt prefix. However, windeployqt may fail to copy extra dlls needed for QtWebKit, and it also doesn't know about new background process executables for QML API

**Comment by taalas** [comment]
Having to copy the extra DLLs manually is totally fine for me. I just want windeployqt to not fail for everything else besides QtWebKit. What exactly do you mean by installing "QtWebKit into Qt prefix"?

**Comment by annulen** [comment]
All files placed side by side with respective files of other Qt modules

**Comment by taalas** [comment]
So you would copy the QtWebKit*.dlls into {Qtdir}/bin/ ?

**Comment by annulen** [comment]
Yes, this is the recommended way. If you build from sources, files are installed there by default. Doing so simplifies use of qmake (no QMAKEPATH dances needed, and module .pri's can be relocatable), also helps with cmake (using QtWebKit via Qt5 COMPONENT or qt5_use_modules() won't work if QtWebKit is installed externally)

**Comment by annulen** [comment]
https://github.com/annulen/webkit/wiki/Using-QtWebKit-in-your-project

**Comment by taalas** [comment]
OK, thanks alot! Very glad this project exists!
