### ISSUE TITLE
prebuild for qt 5.10.x

### ISSUE THREAD

**Issue by aquiles2k** [annulen/webkit#734]
Hi, the current releases contains qt59 in its name so i guess they are not compatible with the current qt5.10.x releases? If so, would it be possible to upload some new binaries? Thanks!

**Comment by annulen** [comment]
You can use binaries from http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/

**Comment by aquiles2k** [comment]
Oh thanks, i didn't know about that link!
