### ISSUE TITLE
Why QtWK does not support Streaming

### ISSUE THREAD

**Issue by FVerbum** [annulen/webkit#738]
Hello.
I have:
Windows 7 x64
VS 2015
I've compiled x32 from freshest source:
http://code.qt.io/cgit/qt/qtwebkit.git branch 5.212
I've compiled my simple web-browser and copied him to Windows 7 x32 (VirtualBox v5.2.6)
But on html5test.com I see this:
![notsupportstreaming](https://user-images.githubusercontent.com/11011056/36951087-4b83f332-2010-11e8-8034-56c5d938031c.png)
What I did wrong ?

**Comment by annulen** [comment]
This feature is only supported with GStreamer-based player. See #334, #698
