### ISSUE TITLE
QtWebKit ready-made binaries for Android

### ISSUE THREAD

**Issue by Aleskey78** [annulen/webkit#745]
Hello,

it would be great if you could also provide ready-made binaries for Android (ARM7).
In the same way you do it e.g. for mingw53_32: https://github.com/annulen/webkit/releases

Thanks,
Aleksey

**Comment by annulen** [comment]
Just making it compile for Android will be enough. When it compiles, Qt's CI system will produce binaries like with other platforms

**Comment by annulen** [comment]
Replaced with #751
