### ISSUE TITLE
How to configure build to not strip binaries?

### ISSUE THREAD

**Issue by paulmenzel** [annulen/webkit#756]
How can the build be configure (under GNU/Linux) so that the debug symbols are not stripped from the binaries?

**Comment by paulmenzel** [comment]
I know of `-DCMAKE_BUILD_TYPE=Debug`, but I believe that is doing more than just not stripping the binaries.

**Comment by annulen** [comment]
Release binaries are not stripped
```
$ file WebKitBuild/Release/lib/libQt5WebKit.so.5.212.0
WebKitBuild/Release/lib/libQt5WebKit.so.5.212.0: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

What you probably want is to add debug information to release binaries, this can be done by setting CMAKE_C_FLAGS and CMAKE_CXX_FLAGS. You can also try CMAKE_BUILD_TYPE=RelWithDebInfo, it should work fine

**Comment by paulmenzel** [comment]
Hmm, I should have checked my build. `file` claims that debug information is included in my build.

I used the configure switches below.

```
        -DPORT=Qt \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_LIBHYPHEN=no
```

```
$ file /usr/lib64/libQt5WebKitWidgets.so.5.212.0
/usr/lib64/libQt5WebKitWidgets.so.5.212.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, with debug_info, not stripped
```

Qt 5.10.1 is built with the switches below.

```
        -nomake examples \
        -opensource \
        -confirm-license \
        -no-strip
```

Is that detected somehow?

**Comment by annulen** [comment]
`-no-strip` is not detected from Qt, and it is default option actually.

**Comment by paulmenzel** [comment]
Ok, made some incorrect assumptions. I deduced the problem from the Qt WebKit 5.9.0 built, which was built with `qmake ${S}/WebKit.pro`.

```
$ file /usr/local/qt5/lib/libQt5WebKitWidgets.so.5.9.0
/usr/local/qt5/lib/libQt5WebKitWidgets.so.5.9.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

**Comment by annulen** [comment]
Yep, old build system inherits all settings from qtbase
