### ISSUE TITLE
FlashPlugin always loaded

### ISSUE THREAD

**Issue by drizt** [annulen/webkit#764]
`QWebSettings::PluginsEnabled` can't disable loading of FlashPlugin. Here test application to reproduce
 it. [checkflash.zip](https://github.com/annulen/webkit/files/2259250/checkflash.zip)

App loads https://whoer.net/#extended this site shows enabled FlashPlugin or no. So `QWebSettings::PluginsEnabled` no affect with FlashPlayer.

**Comment by drizt** [comment]
P.S I checked, in Qt4 it works fine.

**Comment by kevinhendricks** [comment]
See patch at issue #755
