### ISSUE TITLE
Installation webkit - binaries

### ISSUE THREAD

**Issue by ermoschink** [annulen/webkit#766]
Hello!
I'm trying to install compiled binaries.

When you connect a webkit or WebKitWidgets to the QBS project, it generates this message when assembling:

`:-1: ошибка: cannot find C:/Users/ermos/AppData/Roaming/QtProject/qtcreator/qbs/1.12.0/profiles/qtc_Desktop__3fd8c643/modules/Qt/webkit: Permission denied`

Please tell me how it can be fixed?

**Comment by annulen** [comment]
No idea. Maybe QBS needs to have specific "module" for qtwebkit?

**Comment by ermoschink** [comment]
http://doc.qt.io/qbs/qt-modules.html
Судя по данной заметке должна поддерживаться сразу после установки.
Может быть Вы сможет попробовать собрать проект(QBS) с подключенным webkit.
Подозреваю что проблема в установке.

**Comment by annulen** [comment]
Похоже, что при создании профиля qbs пытается открыть .prl файлы lib/libQt5WebKit.prl и lib/libQt5WebKitWidgets.prl, а я их не создаю

**Comment by ermoschink** [comment]
В том и дело что файлы создаются. Но он не поможет получить к ним доступ.

**Comment by annulen** [comment]
Система сборки QtWebKit в данный момент не создает и не устанавливает prl файлы. Возможно, в качестсве воркэраунда подойдет создание этих файлов вручную, например скопировать prl для другого модуля и поправить

**Comment by annulen** [comment]
Добавлять генерацию prl я не планирую, но готов рассмотреть патчи на эту тему
