### ISSUE TITLE
Problems building with very latest VS 2017

### ISSUE THREAD

**Issue by dougmassay** [annulen/webkit#769]
Visual Studio 2017 v15.8.1
Got this error while compiling WebCore:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.`

I was able to move past it by brute forcing  -D_DISABLE_EXTENDED_ALIGNED_STORAGE in WebCore's PlatformQt.cmake file, but I assume something a bit more graceful is probably desired.

Then when compiling WebKit2 I ran into the following issue:

`-c C:\qt5\qtwebkit\Source\WebKit2\DatabaseProcess\IndexedDB\WebIDBConnectionToClient.cpp`

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(912): error C2139: 'WebCore::IDBResultData': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_assignable'`

`C:\qt5-build\qtwebkit\release\DerivedSources\WebKit2\WebIDBConnectionToServerMessages.h(35): note: see declaration of 'WebCore::IDBResultData'`

I'm at a bit of a loss as to how best to proceed where generated/derived sources are involved. I'm hoping there's some compiler version defines somewhere that just need tweaked to account for the new compiler version (19.15.26726) or something.

**Comment by dougmassay** [comment]
Once I disabled WebKit2, the build completed just fine (after adding the  -D_DISABLE_EXTENDED_ALIGNED_STORAGE define, of course). So it appears that only WebKit2 is having problems with VS2017 v15.8.1. It's possible that the problem could be related to the latest Windows SDK that ships with 15.8.1, but I won't know until I do some more experimenting. I know I ran into a problem building libxml2 with the latest VS2017 + the latest Windows 10 SDK (which now ships with its own slightly mangled ICU libs) using my standard procedure. It built fine when targeting Windows 8.1, though. Perhaps it's something similar here. That would certainly be nice!

**Comment by herbmillerjr** [comment]
You have to _enable_ it, not disable. Open [upstream bug](https://bugreports.qt.io/browse/QTBUG-70232?jql=project%20%3D%20QTBUG%20AND%20component%20%3D%20WebKit) as well. Also for [Qt itself](https://codereview.qt-project.org/#/c/235205/).

@annulen I created PR #773 to address.

**Comment by dougmassay** [comment]
Thanks! I could have sworn I'd tried it both ways with no change RE the later 2139 errors, but I must have been wrong.

Thanks for the upstream reports.

**Comment by annulen** [comment]
I've fixed issue with `__is_assignable` in WebKit2 in ce3c2e6fbfa6a7bfe43fd5ab4cd62b1937e22391 and d6bf9b7a5a72ec63236f3f2d0eabc20913309793
