### ISSUE TITLE
Support HSTS

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#99]
https://bugreports.qt.io/browse/QTBUG-18030
https://bugs.webkit.org/show_bug.cgi?id=102478
https://bugzilla.gnome.org/show_bug.cgi?id=628298

The-Compiler/qutebrowser#665

Probably we should implement it as a fake redirect internally

**Comment by annulen** [comment]
Qt 5.9 finaly adds HSTS support and API to control it: 
https://codereview.qt-project.org/#/c/181597/
https://codereview.qt-project.org/#/c/183103/

Questions for @Emdek and @The-Compiler:
* By default HSTS is disabled in freshly created QNAM. Should QtWebKit enable it by default for QNAM's it creates itself?
* Do we need any specific API on QtWebKit side? It's possible to control behavior of QNAM for each QWebPage directly, but maybe we need global settings?

**Comment by annulen** [comment]
@Vitallium ^

**Comment by Emdek** [comment]
@annulen, I would vote for enabling it by default and I don't see need for new API.

**Comment by The-Compiler** [comment]
I agree it should be turned on by default. Things breaking with broken servers is a smaller concern than the security improvements this brings, IMHO.

As for API - what kind of API are you thinking of?

**Comment by annulen** [comment]
>Things breaking with broken servers is a smaller concern than the security improvements this brings, IMHO.
In case of browser broken connection is probably better outcome than potentially allowing attacks. (In case of non-browser QNAM applications considerations may be different)

>As for API - what kind of API are you thinking of?
Global on/off and addStrictTransportSecurityHosts, affecting all QNAMs that will be created internally

**Comment by Emdek** [comment]
Such API would either require at least Qt 5.9 or have no effect for older versions.

**Comment by The-Compiler** [comment]
Are QNAMs created internally only when constructing a QWebPage or elsewhere too? If it's only there, I think it's simple enough to use the QNAM APIs.

**Comment by annulen** [comment]
Fixed in e6975cd79ccbe897b8ff6a0a62b6cde490d4aefe and https://codereview.qt-project.org/191433

**Comment by annulen** [comment]
Potential issue is related to private mode: when HSTS is enabled, it's possible to use it for identification of user, see [1]. With current implementation this issue does not impose much concern, because HSTS policy cache is not persistent by default and it's the application's responsibility to save or not save this cache, or clear it when requested

[1] https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#Privacy_issues
